/*
* TLS record layer implementation for TLS 1.3
* (C) 2022 Jack Lloyd
*     2022 Hannes Rantzsch, René Meusel - neXenio GmbH
*     2026 Amos Treiber, René Meusel - Rohde & Schwarz Networks and Cybersecurity GmbH
*
* Botan is released under the Simplified BSD License (see license.txt)
*/

#include <botan/internal/tls_record_layer_13.h>

#if defined(BOTAN_HAS_DTLS_13)
   #include <botan/internal/tls_record_layer_dtls13.h>
#endif

#include <botan/tls_alert.h>
#include <botan/tls_exceptn.h>
#include <botan/tls_policy.h>
#include <botan/tls_version.h>
#include <botan/internal/buffer_slicer.h>
#include <botan/internal/concat_util.h>
#include <botan/internal/ct_utils.h>
#include <botan/internal/int_utils.h>
#include <botan/internal/loadstor.h>
#include <botan/internal/tls_cipher_state.h>
#include <algorithm>
#include <deque>

namespace Botan::TLS {

namespace {

bool verify_change_cipher_spec(std::span<const uint8_t> data) {
   // RFC 8446 5.
   //    An implementation may receive an unencrypted record of type
   //    change_cipher_spec consisting of the single byte value 0x01
   //    at any time [...]. An implementation which receives any other
   //    change_cipher_spec value or which receives a protected
   //    change_cipher_spec record MUST abort the handshake [...].
   constexpr size_t expected_fragment_length = 1;
   constexpr uint8_t expected_fragment_byte = 0x01;
   return (data.size() == expected_fragment_length && data.front() == expected_fragment_byte);
}

class TLS_Record_Layer final : public Record_Layer {
   public:
      explicit TLS_Record_Layer(Connection_Side side, std::shared_ptr<const Policy> policy);

      bool copy_data(std::span<const uint8_t> data_from_peer, bool has_cryptographic_association) override;
      ReadResult<Record_Content> next_record(Cipher_State* cipher_state = nullptr) override;
      std::vector<MarshalledRecord> prepare_records(Record_Type type,
                                                    std::span<const uint8_t> payload,
                                                    Cipher_State* cipher_state) const override;
      std::vector<MarshalledRecord> prepare_records(const PreparedHandshakeMessageFlight& flight,
                                                    Cipher_State* cipher_state = nullptr) const override;

      void clear_read_buffer() override;

      uint16_t record_payload_size_limit(const Policy& policy, Cipher_State* cipher_state = nullptr) const override;

   private:
      std::deque<Record_TLS> m_incoming_records;
};

TLS_Record_Layer::TLS_Record_Layer(Connection_Side side, std::shared_ptr<const Policy> policy) :
      Record_Layer(side,
                   std::move(policy),

                   // RFC 8446 5.1
                   //    legacy_record_version: MUST be set to 0x0303 for all records
                   //       generated by a TLS 1.3 implementation other than an initial
                   //       ClientHello [...], where it MAY also be 0x0301 for compatibility
                   //       purposes.
                   //
                   // Additionally, older peers might send other values while requesting a
                   // protocol downgrade. I.e. we need to be able to tolerate/emit legacy
                   // values until we negotiated a TLS 1.3 compliant connection.
                   //
                   // As a client: we may initially emit the compatibility version and
                   //              accept a wider range of incoming legacy record versions.
                   // As a server: we start with emitting the specified legacy version of 0x0303
                   //              but must also allow a wider range of incoming legacy values.
                   //
                   // Once TLS 1.3 is negotiateed, the implementations will disable these
                   // compatibility modes accordingly or a protocol downgrade will transfer
                   // the marshalling responsibility to our TLS 1.2 implementation.

                   /* sending_compat_mode = */ side == Connection_Side::Client,
                   /* receiving_compat_mode = */ true) {}

bool TLS_Record_Layer::copy_data(std::span<const uint8_t> data_from_peer, bool has_cryptographic_association) {
   BOTAN_UNUSED(has_cryptographic_association);

   while(!data_from_peer.empty()) {
      auto& record = [&]() -> Record_TLS& {
         if(m_incoming_records.empty() || m_incoming_records.back().complete()) {
            return m_incoming_records.emplace_back();
         } else {
            return m_incoming_records.back();
         }
      }();

      BOTAN_DEBUG_ASSERT(!record.complete());
      const size_t consumed = record.append(data_from_peer);
      BOTAN_ASSERT_NOMSG(consumed <= data_from_peer.size());
      data_from_peer = data_from_peer.subspan(consumed);
   }

   // We don't ever drop data in TLS, we do that in DTLS only.
   return true;
}

std::vector<MarshalledRecord> TLS_Record_Layer::prepare_records(const Record_Type type,
                                                                std::span<const uint8_t> data,
                                                                Cipher_State* cipher_state) const {
   // RFC 8446 5.
   //    Note that [change_cipher_spec records] may appear at a point at the
   //    handshake where the implementation is expecting protected records.
   //
   // RFC 8446 5.
   //    An implementation which receives [...] a protected change_cipher_spec
   //    record MUST abort the handshake [...].
   //
   // ... hence, CHANGE_CIPHER_SPEC is never protected, even if a usable cipher
   // state was passed to this method.
   const bool protect = cipher_state != nullptr && type != Record_Type::ChangeCipherSpec;

   // RFC 8446 5.1
   BOTAN_ASSERT(protect || type != Record_Type::ApplicationData,
                "Application Data records MUST NOT be written to the wire unprotected");

   // RFC 8446 5.1
   //   "MUST NOT sent zero-length fragments of Handshake types"
   //   "a record with an Alert type MUST contain exactly one message" [of non-zero length]
   //   "Zero-length fragments of Application Data MAY be sent"
   BOTAN_ASSERT(!data.empty() || type == Record_Type::ApplicationData,
                "zero-length fragments of types other than application data are not allowed");

   if(type == Record_Type::ChangeCipherSpec && !verify_change_cipher_spec(data)) {
      throw Invalid_Argument("TLS 1.3 deprecated CHANGE_CIPHER_SPEC");
   }

   // RFC 8446 5.2
   //    type:  The TLSPlaintext.type value containing the content type of the record.
   constexpr size_t content_type_tag_length = 1;

   // RFC 8449 4.
   //    When the "record_size_limit" extension is negotiated, an endpoint
   //    MUST NOT generate a protected record with plaintext that is larger
   //    than the RecordSizeLimit value it receives from its peer.
   //    Unprotected messages are not subject to this limit.
   //
   // RFC 9846 5.4
   //    [T]he full encoded TLSInnerPlaintext MUST NOT exceed 2^14 + 1 octets.
   //    If the maximum fragment length is reduced -- as for example by the
   //    record_size_limit extension from RFC 8449 -- then the reduced limit
   //    applies to the full plaintext, including the content type and padding.
   //
   // Hence, this calculates the maximum amount of actual application data
   // payload bytes that can be transferred in a single record (assuming no
   // further padding is applied by the policy).
   const size_t max_plaintext_payload_size =
      (protect) ? outgoing_record_size_limit() - content_type_tag_length : static_cast<uint16_t>(MAX_PLAINTEXT_SIZE);

   const auto records = std::max(ceil_division(data.size(), max_plaintext_payload_size), size_t(1));

   std::vector<MarshalledRecord> output;
   output.reserve(records);

   BufferSlicer bs(data);

   // RFC 9846 5.1
   //    Zero-length fragments of Application Data [...] MAY be sent, as they
   //    are potentially useful as a traffic analysis countermeasure.
   //
   // For protected records we need to write at least one encrypted fragment,
   // even if the plaintext size is zero. This happens only for Application
   // Data types.
   BOTAN_ASSERT_NOMSG(!bs.empty() || protect);

   do /* NOLINT(*-avoid-do-while)*/ {
      const size_t pt_size = std::min(bs.remaining(), max_plaintext_payload_size);
      const auto pt_fragment = bs.take(pt_size);

      if(protect) {
         const size_t pt_size_with_type_tag = pt_size + content_type_tag_length;
         const size_t max_record_size = outgoing_record_size_limit();

         // Don't even bother consulting the policy if we already filled the
         // record fully, because then we can't add any padding anyway.
         // If the user requests more padding than we can actually add, we will
         // truncate the padding to fill up the record entirely.
         const size_t padding_length =
            (pt_size_with_type_tag < max_record_size)
               ? std::min(policy().record_padding_bytes(pt_size_with_type_tag), max_record_size - pt_size_with_type_tag)
               : 0;
         BOTAN_ASSERT_NOMSG(pt_size_with_type_tag + padding_length <= max_record_size);

         output.push_back(cipher_state->protect_record(type, pt_fragment, padding_length));
      } else {
         // RFC 9846 5.1
         //    MUST be set to 0x0303 for all records generated by a TLS 1.3
         //    implementation other than an initial ClientHello [...], where
         //    it MAY also be 0x0301 for compatibility purposes.
         const auto legacy_record_version = (sending_compat_mode()) ? Protocol_Version::TLS_V10  //
                                                                    : Protocol_Version::TLS_V12;

         // RFC 9846 5.1
         //    type:                  The higher-level protocol used to process
         //                           the enclosed fragment.
         //    legacy_record_version: [see above]
         //    length:                The length (in bytes) of the following
         //                           TLSPlaintext.fragment.
         const auto header = Record_TLS::serialize_header(type,                   //
                                                          legacy_record_version,  //
                                                          checked_cast_to<uint16_t>(pt_fragment.size()));

         MarshalledRecord& plaintext_record = output.emplace_back();
         plaintext_record.get().reserve(header.size() + pt_fragment.size());
         plaintext_record.get().insert(plaintext_record.end(), header.begin(), header.end());
         plaintext_record.get().insert(plaintext_record.end(), pt_fragment.begin(), pt_fragment.end());
      }
   }

   while(!bs.empty());

   BOTAN_ASSERT_NOMSG(output.size() == records);
   return output;
}

std::vector<MarshalledRecord> TLS_Record_Layer::prepare_records(const PreparedHandshakeMessageFlight& flight,
                                                                Cipher_State* cipher_state) const {
   const auto* data = std::get_if<MarshalledHandshakeMessageFlight>(&flight);
   BOTAN_ARG_CHECK(data != nullptr, "Flight must be a MarshalledHandshakeMessageFlight");

   // Here, `data` is a flat byte vector that (potentially) contains multiple
   // marshalled handshake messages. We simply delegate it to the other overload
   // of `prepare_records` that handles the actual record marshalling.
   return prepare_records(Record_Type::Handshake, std::span{*data}, cipher_state);
}

uint16_t TLS_Record_Layer::record_payload_size_limit(const Policy& policy, Cipher_State* cipher_state) const {
   BOTAN_UNUSED(policy);  // not relevant for TLS
   constexpr uint16_t content_type_tag_length = 1;

   // RFC 8449 4.
   //    When the "record_size_limit" extension is negotiated, an endpoint
   //    MUST NOT generate a protected record with plaintext that is larger
   //    than the RecordSizeLimit value it receives from its peer.
   //    Unprotected messages are not subject to this limit.
   return (cipher_state != nullptr) ? outgoing_record_size_limit() - content_type_tag_length
                                    : static_cast<uint16_t>(MAX_PLAINTEXT_SIZE);
}

Record_Layer::ReadResult<Record_Content> TLS_Record_Layer::next_record(Cipher_State* cipher_state) {
   // Special case: on the record boundary we don't actually need any more data
   // and we also don't want to be the know-it-all that now demands exactly
   // enough bytes to start parsing the next record header.
   if(m_incoming_records.empty()) {
      return BytesNeeded(0);
   }

   if(!m_incoming_records.front().complete()) {
      return m_incoming_records.front().missing_bytes_hint();
   }

   auto record = std::move(m_incoming_records.front());
   m_incoming_records.pop_front();

   // RFC 9846 Appendix E
   //    Prior versions of TLS used the record layer version number [...] for
   //    various purposes. As of TLS 1.3, this field is deprecated. The value
   //    [...] MAY be validated to match the fixed constant value.
   //
   // RFC 9846 5.1
   //    legacy_record_version:  MUST be set to 0x0303 for all records generated
   //                            by a TLS 1.3 implementation.
   //
   // If `receiving_compat_mode()` is true, we don't validate the legacy version
   // and once it is disabled by the state-machine we enforce the specified
   // fixed value of 0x0303 (TLS 1.2) for all incoming records.
   if(!receiving_compat_mode() && record.legacy_version() != Protocol_Version::TLS_V12) {
      throw TLS_Exception(Alert::IllegalParameter, "Received unexpected record version");
   }

   // After the key exchange phase of the handshake is completed and record protection is engaged,
   // cipher_state is set. At this point, only protected traffic (and CCS) is allowed.
   //
   // RFC 9846 2.
   //    -  Key Exchange: Establish shared keying material and select the
   //       cryptographic parameters.  Everything after this phase is
   //       encrypted.
   // RFC 9846 5.
   //    An implementation may receive an unencrypted [CCS] at any time
   if(cipher_state != nullptr && record.type() != Record_Type::ApplicationData &&
      record.type() != Record_Type::ChangeCipherSpec &&
      (!cipher_state->must_expect_unprotected_alert_traffic() || record.type() != Record_Type::Alert)) {
      throw TLS_Exception(Alert::UnexpectedMessage, "unprotected record received where protected traffic was expected");
   }

   if(record.type() == Record_Type::ChangeCipherSpec && !verify_change_cipher_spec(record.payload())) {
      throw TLS_Exception(Alert::UnexpectedMessage, "malformed change cipher spec record received");
   }

   if(record.type() != Record_Type::ApplicationData) {
      return Record_Content{
         .type = record.type(),
         .sequence_number = std::nullopt,
         .payload = record.take_payload(),
         .epoch = std::nullopt,
      };
   } else {
      if(cipher_state == nullptr) {
         // This could also mean a misuse of the interface, i.e. failing to
         // provide a valid cipher_state to parse_records when receiving valid
         // (encrypted) Application Data.
         throw TLS_Exception(Alert::UnexpectedMessage, "premature Application Data received");
      }

      return cipher_state->deprotect_record(std::move(record), incoming_record_size_limit());
   }
}

void TLS_Record_Layer::clear_read_buffer() {
   m_incoming_records.clear();
}

}  // namespace

std::unique_ptr<Record_Layer> Record_Layer::create(Connection_Side side,
                                                   TLS_Flavor flavor,
                                                   std::shared_ptr<const Policy> policy) {
   if(flavor == TLS_Flavor::DTLS) {
#if defined(BOTAN_HAS_DTLS_13)
      return std::make_unique<DTLS_Record_Layer>(side, std::move(policy));
#else
      throw Not_Implemented("DTLS 1.3 is not enabled in this build of Botan");
#endif
   } else {
      return std::make_unique<TLS_Record_Layer>(side, std::move(policy));
   }
}

Record_Layer::Record_Layer(Connection_Side side,
                           std::shared_ptr<const Policy> policy,
                           bool sending_compat_mode,
                           bool receiving_compat_mode) :
      m_side(side),
      m_policy(std::move(policy)),
      m_outgoing_record_size_limit(MAX_PLAINTEXT_SIZE + 1 /* content type byte */),
      m_incoming_record_size_limit(MAX_PLAINTEXT_SIZE + 1 /* content type byte */),
      m_sending_compat_mode(sending_compat_mode),
      m_receiving_compat_mode(receiving_compat_mode) {}

void Record_Layer::set_record_size_limits(const uint16_t outgoing_limit, const uint16_t incoming_limit) {
   BOTAN_ARG_CHECK(outgoing_limit >= 64, "Invalid outgoing record size limit");
   BOTAN_ARG_CHECK(incoming_limit >= 64 && incoming_limit <= MAX_PLAINTEXT_SIZE + 1,
                   "Invalid incoming record size limit");

   // RFC 8449 4.
   //    Even if a larger record size limit is provided by a peer, an endpoint
   //    MUST NOT send records larger than the protocol-defined limit, unless
   //    explicitly allowed by a future TLS version or extension.
   m_outgoing_record_size_limit = std::min(outgoing_limit, static_cast<uint16_t>(MAX_PLAINTEXT_SIZE + 1));
   m_incoming_record_size_limit = incoming_limit;
}

}  // namespace Botan::TLS
