/*
* This file was automatically generated by ./src/scripts/dev_tools/gen_oids.py on 2025-06-03
*
* All manual edits to this file will be lost. Edit the script then regenerate this source file.
*
* Botan is released under the Simplified BSD License (see license.txt)
*/

#include <botan/internal/oid_map.h>

#include <initializer_list>
#include <unordered_map>

namespace Botan {

namespace {

// The hash can collide so we must verify the actual value matches before returning
std::optional<std::string_view> if_match(const OID& oid, std::initializer_list<uint32_t> val, std::string_view name) {
   if(oid.matches(val)) {
      return name;
   } else {
      return {};
   }
}

std::optional<OID> if_match(std::string_view req, std::string_view actual, std::initializer_list<uint32_t> oid) {
   if(req == actual) {
      return OID(oid);
   } else {
      return {};
   }
}

uint32_t hash_oid_name(std::string_view s) {
   uint32_t hash = 0x411ECD00 + static_cast<uint32_t>(s.size());

   for(char c : s) {
      hash *= 251;
      hash += c;
   }

   return hash & 0x00FFFFFF;
}

}  // namespace

//static
std::optional<std::string_view> OID_Map::lookup_static_oid(const OID& oid) {
   const uint32_t hc = static_cast<uint32_t>(oid.hash_code() & 0x00FFFFFF);

   // clang-format off
   switch(hc) {

      case 0x0483B8:
         return if_match(oid, {1, 3, 14, 3, 2, 7}, "DES/CBC");
      case 0x0483CB:
         return if_match(oid, {1, 3, 14, 3, 2, 26}, "SHA-1");
      case 0x05B380:
         return if_match(oid, {1, 2, 410, 200004, 1, 4}, "SEED/CBC");
      case 0x0BF327:
         return if_match(oid, {1, 2, 840, 10045, 3, 1, 1}, "secp192r1");
      case 0x0BF328:
         return if_match(oid, {1, 2, 840, 10045, 3, 1, 2}, "x962_p192v2");
      case 0x0BF329:
         return if_match(oid, {1, 2, 840, 10045, 3, 1, 3}, "x962_p192v3");
      case 0x0BF32A:
         return if_match(oid, {1, 2, 840, 10045, 3, 1, 4}, "x962_p239v1");
      case 0x0BF32B:
         return if_match(oid, {1, 2, 840, 10045, 3, 1, 5}, "x962_p239v2");
      case 0x0BF32C:
         return if_match(oid, {1, 2, 840, 10045, 3, 1, 6}, "x962_p239v3");
      case 0x0BF32D:
         return if_match(oid, {1, 2, 840, 10045, 3, 1, 7}, "secp256r1");
      case 0x0CF72A:
         return if_match(oid, {1, 2, 840, 10045, 4, 3, 1}, "ECDSA/SHA-224");
      case 0x0CF72B:
         return if_match(oid, {1, 2, 840, 10045, 4, 3, 2}, "ECDSA/SHA-256");
      case 0x0CF72C:
         return if_match(oid, {1, 2, 840, 10045, 4, 3, 3}, "ECDSA/SHA-384");
      case 0x0CF72D:
         return if_match(oid, {1, 2, 840, 10045, 4, 3, 4}, "ECDSA/SHA-512");
      case 0x0D8FCB:
         return if_match(oid, {1, 3, 36, 3, 3, 1, 2}, "RSA/PKCS1v15(RIPEMD-160)");
      case 0x0E7B71:
         return if_match(oid, {1, 3, 101, 110}, "X25519");
      case 0x0E7B72:
         return if_match(oid, {1, 3, 101, 111}, "X448");
      case 0x0E7B73:
         return if_match(oid, {1, 3, 101, 112}, "Ed25519");
      case 0x0E7B74:
         return if_match(oid, {1, 3, 101, 113}, "Ed448");
      case 0x1320A8:
         return if_match(oid, {2, 5, 4, 3}, "X520.CommonName");
      case 0x1320A9:
         return if_match(oid, {2, 5, 4, 4}, "X520.Surname");
      case 0x1320AA:
         return if_match(oid, {2, 5, 4, 5}, "X520.SerialNumber");
      case 0x1320AB:
         return if_match(oid, {2, 5, 4, 6}, "X520.Country");
      case 0x1320AC:
         return if_match(oid, {2, 5, 4, 7}, "X520.Locality");
      case 0x1320AD:
         return if_match(oid, {2, 5, 4, 8}, "X520.State");
      case 0x1320AE:
         return if_match(oid, {2, 5, 4, 9}, "X520.StreetAddress");
      case 0x1320AF:
         return if_match(oid, {2, 5, 4, 10}, "X520.Organization");
      case 0x1320B0:
         return if_match(oid, {2, 5, 4, 11}, "X520.OrganizationalUnit");
      case 0x1320B1:
         return if_match(oid, {2, 5, 4, 12}, "X520.Title");
      case 0x1320CF:
         return if_match(oid, {2, 5, 4, 42}, "X520.GivenName");
      case 0x1320D0:
         return if_match(oid, {2, 5, 4, 43}, "X520.Initials");
      case 0x1320D1:
         return if_match(oid, {2, 5, 4, 44}, "X520.GenerationalQualifier");
      case 0x1320D3:
         return if_match(oid, {2, 5, 4, 46}, "X520.DNQualifier");
      case 0x1320E6:
         return if_match(oid, {2, 5, 4, 65}, "X520.Pseudonym");
      case 0x1339CC:
         return if_match(oid, {2, 5, 29, 14}, "X509v3.SubjectKeyIdentifier");
      case 0x1339CD:
         return if_match(oid, {2, 5, 29, 15}, "X509v3.KeyUsage");
      case 0x1339CE:
         return if_match(oid, {2, 5, 29, 16}, "X509v3.PrivateKeyUsagePeriod");
      case 0x1339CF:
         return if_match(oid, {2, 5, 29, 17}, "X509v3.SubjectAlternativeName");
      case 0x1339D0:
         return if_match(oid, {2, 5, 29, 18}, "X509v3.IssuerAlternativeName");
      case 0x1339D1:
         return if_match(oid, {2, 5, 29, 19}, "X509v3.BasicConstraints");
      case 0x1339D2:
         return if_match(oid, {2, 5, 29, 20}, "X509v3.CRLNumber");
      case 0x1339D3:
         return if_match(oid, {2, 5, 29, 21}, "X509v3.ReasonCode");
      case 0x1339D5:
         return if_match(oid, {2, 5, 29, 23}, "X509v3.HoldInstructionCode");
      case 0x1339D6:
         return if_match(oid, {2, 5, 29, 24}, "X509v3.InvalidityDate");
      case 0x1339DA:
         return if_match(oid, {2, 5, 29, 28}, "X509v3.CRLIssuingDistributionPoint");
      case 0x1339DC:
         return if_match(oid, {2, 5, 29, 30}, "X509v3.NameConstraints");
      case 0x1339DD:
         return if_match(oid, {2, 5, 29, 31}, "X509v3.CRLDistributionPoints");
      case 0x1339DE:
         return if_match(oid, {2, 5, 29, 32}, "X509v3.CertificatePolicies");
      case 0x1339E1:
         return if_match(oid, {2, 5, 29, 35}, "X509v3.AuthorityKeyIdentifier");
      case 0x1339E2:
         return if_match(oid, {2, 5, 29, 36}, "X509v3.PolicyConstraints");
      case 0x1339E3:
         return if_match(oid, {2, 5, 29, 37}, "X509v3.ExtendedKeyUsage");
      case 0x30A083:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 3029, 1, 2, 1}, "ElGamal");
      case 0x30A386:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 3029, 1, 5, 1}, "OpenPGP.Curve25519");
      case 0x34E263:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 12, 1, 1}, "SphincsPlus-shake-128s-r3.1");
      case 0x34E264:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 12, 1, 2}, "SphincsPlus-shake-128f-r3.1");
      case 0x34E265:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 12, 1, 3}, "SphincsPlus-shake-192s-r3.1");
      case 0x34E266:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 12, 1, 4}, "SphincsPlus-shake-192f-r3.1");
      case 0x34E267:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 12, 1, 5}, "SphincsPlus-shake-256s-r3.1");
      case 0x34E268:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 12, 1, 6}, "SphincsPlus-shake-256f-r3.1");
      case 0x34E364:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 12, 2, 1}, "SphincsPlus-sha2-128s-r3.1");
      case 0x34E365:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 12, 2, 2}, "SphincsPlus-sha2-128f-r3.1");
      case 0x34E366:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 12, 2, 3}, "SphincsPlus-sha2-192s-r3.1");
      case 0x34E367:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 12, 2, 4}, "SphincsPlus-sha2-192f-r3.1");
      case 0x34E368:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 12, 2, 5}, "SphincsPlus-sha2-256s-r3.1");
      case 0x34E369:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 12, 2, 6}, "SphincsPlus-sha2-256f-r3.1");
      case 0x34E465:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 12, 3, 1}, "SphincsPlus-haraka-128s-r3.1");
      case 0x34E466:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 12, 3, 2}, "SphincsPlus-haraka-128f-r3.1");
      case 0x34E467:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 12, 3, 3}, "SphincsPlus-haraka-192s-r3.1");
      case 0x34E468:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 12, 3, 4}, "SphincsPlus-haraka-192f-r3.1");
      case 0x34E469:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 12, 3, 5}, "SphincsPlus-haraka-256s-r3.1");
      case 0x34E46A:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 12, 3, 6}, "SphincsPlus-haraka-256f-r3.1");
      case 0x369E45:
         return if_match(oid, {2, 16, 840, 1, 113730, 1, 13}, "Certificate Comment");
      case 0x3709D5:
         return if_match(oid, {1, 3, 36, 3, 3, 2, 8, 1, 1, 1}, "brainpool160r1");
      case 0x3709D7:
         return if_match(oid, {1, 3, 36, 3, 3, 2, 8, 1, 1, 3}, "brainpool192r1");
      case 0x3709D9:
         return if_match(oid, {1, 3, 36, 3, 3, 2, 8, 1, 1, 5}, "brainpool224r1");
      case 0x3709DB:
         return if_match(oid, {1, 3, 36, 3, 3, 2, 8, 1, 1, 7}, "brainpool256r1");
      case 0x3709DD:
         return if_match(oid, {1, 3, 36, 3, 3, 2, 8, 1, 1, 9}, "brainpool320r1");
      case 0x3709DF:
         return if_match(oid, {1, 3, 36, 3, 3, 2, 8, 1, 1, 11}, "brainpool384r1");
      case 0x3709E1:
         return if_match(oid, {1, 3, 36, 3, 3, 2, 8, 1, 1, 13}, "brainpool512r1");
      case 0x38D4B2:
         return if_match(oid, {1, 2, 392, 200011, 61, 1, 1, 1, 2}, "Camellia-128/CBC");
      case 0x38D4B3:
         return if_match(oid, {1, 2, 392, 200011, 61, 1, 1, 1, 3}, "Camellia-192/CBC");
      case 0x38D4B4:
         return if_match(oid, {1, 2, 392, 200011, 61, 1, 1, 1, 4}, "Camellia-256/CBC");
      case 0x39C422:
         return if_match(oid, {1, 2, 840, 10040, 4, 1}, "DSA");
      case 0x39C424:
         return if_match(oid, {1, 2, 840, 10040, 4, 3}, "DSA/SHA-1");
      case 0x3B9695:
         return if_match(oid, {1, 2, 840, 113549, 1, 9, 16, 3, 6}, "KeyWrap.TripleDES");
      case 0x3B9697:
         return if_match(oid, {1, 2, 840, 113549, 1, 9, 16, 3, 8}, "Compression.Zlib");
      case 0x3B96A0:
         return if_match(oid, {1, 2, 840, 113549, 1, 9, 16, 3, 17}, "HSS-LMS");
      case 0x3B96A1:
         return if_match(oid, {1, 2, 840, 113549, 1, 9, 16, 3, 18}, "ChaCha20Poly1305");
      case 0x3E86B8:
         return if_match(oid, {1, 3, 6, 1, 5, 5, 7, 1, 1}, "PKIX.AuthorityInformationAccess");
      case 0x3E86BE:
         return if_match(oid, {1, 3, 6, 1, 5, 5, 7, 1, 7}, "PKIX.IpAddrBlocks");
      case 0x3E86BF:
         return if_match(oid, {1, 3, 6, 1, 5, 5, 7, 1, 8}, "PKIX.AutonomousSysIds");
      case 0x3E86D1:
         return if_match(oid, {1, 3, 6, 1, 5, 5, 7, 1, 26}, "PKIX.TNAuthList");
      case 0x3E88BA:
         return if_match(oid, {1, 3, 6, 1, 5, 5, 7, 3, 1}, "PKIX.ServerAuth");
      case 0x3E88BB:
         return if_match(oid, {1, 3, 6, 1, 5, 5, 7, 3, 2}, "PKIX.ClientAuth");
      case 0x3E88BC:
         return if_match(oid, {1, 3, 6, 1, 5, 5, 7, 3, 3}, "PKIX.CodeSigning");
      case 0x3E88BD:
         return if_match(oid, {1, 3, 6, 1, 5, 5, 7, 3, 4}, "PKIX.EmailProtection");
      case 0x3E88BE:
         return if_match(oid, {1, 3, 6, 1, 5, 5, 7, 3, 5}, "PKIX.IPsecEndSystem");
      case 0x3E88BF:
         return if_match(oid, {1, 3, 6, 1, 5, 5, 7, 3, 6}, "PKIX.IPsecTunnel");
      case 0x3E88C0:
         return if_match(oid, {1, 3, 6, 1, 5, 5, 7, 3, 7}, "PKIX.IPsecUser");
      case 0x3E88C1:
         return if_match(oid, {1, 3, 6, 1, 5, 5, 7, 3, 8}, "PKIX.TimeStamping");
      case 0x3E88C2:
         return if_match(oid, {1, 3, 6, 1, 5, 5, 7, 3, 9}, "PKIX.OCSPSigning");
      case 0x3E8DC3:
         return if_match(oid, {1, 3, 6, 1, 5, 5, 7, 8, 5}, "PKIX.XMPPAddr");
      case 0x3EB5E7:
         return if_match(oid, {1, 3, 6, 1, 5, 5, 7, 48, 1}, "PKIX.OCSP");
      case 0x3EB5E8:
         return if_match(oid, {1, 3, 6, 1, 5, 5, 7, 48, 2}, "PKIX.CertificateAuthorityIssuers");
      case 0x3ECC25:
         return if_match(oid, {1, 2, 840, 10045, 2, 1}, "ECDSA");
      case 0x3ECE27:
         return if_match(oid, {1, 2, 840, 10045, 4, 1}, "ECDSA/SHA-1");
      case 0x3FCE26:
         return if_match(oid, {1, 2, 840, 10046, 2, 1}, "DH");
      case 0x46C5C8:
         return if_match(oid, {1, 3, 36, 3, 2, 1}, "RIPEMD-160");
      case 0x49E1F9:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 311, 20, 2, 2}, "Microsoft SmartcardLogon");
      case 0x49E1FA:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 311, 20, 2, 3}, "Microsoft UPN");
      case 0x4D17DE:
         return if_match(oid, {2, 5, 29, 32, 0}, "X509v3.AnyPolicy");
      case 0x4D77E7:
         return if_match(oid, {1, 2, 410, 200004, 1, 100, 4, 3}, "ECKCDSA/SHA-1");
      case 0x4D77E8:
         return if_match(oid, {1, 2, 410, 200004, 1, 100, 4, 4}, "ECKCDSA/SHA-224");
      case 0x4D77E9:
         return if_match(oid, {1, 2, 410, 200004, 1, 100, 4, 5}, "ECKCDSA/SHA-256");
      case 0x623B2B:
         return if_match(oid, {1, 2, 643, 7, 1, 1, 1, 1}, "GOST-34.10-2012-256");
      case 0x623B2C:
         return if_match(oid, {1, 2, 643, 7, 1, 1, 1, 2}, "GOST-34.10-2012-512");
      case 0x623C2D:
         return if_match(oid, {1, 2, 643, 7, 1, 1, 2, 2}, "Streebog-256");
      case 0x623C2E:
         return if_match(oid, {1, 2, 643, 7, 1, 1, 2, 3}, "Streebog-512");
      case 0x623D2E:
         return if_match(oid, {1, 2, 643, 7, 1, 1, 3, 2}, "GOST-34.10-2012-256/Streebog-256");
      case 0x623D2F:
         return if_match(oid, {1, 2, 643, 7, 1, 1, 3, 3}, "GOST-34.10-2012-512/Streebog-512");
      case 0x63DF27:
         return if_match(oid, {1, 2, 643, 2, 2, 3}, "GOST-34.10/GOST-R-34.11-94");
      case 0x63DF37:
         return if_match(oid, {1, 2, 643, 2, 2, 19}, "GOST-34.10");
      case 0x6BB4E6:
         return if_match(oid, {0, 3, 4401, 5, 3, 1, 9, 6}, "Camellia-128/GCM");
      case 0x6BB4FA:
         return if_match(oid, {0, 3, 4401, 5, 3, 1, 9, 26}, "Camellia-192/GCM");
      case 0x6BB50E:
         return if_match(oid, {0, 3, 4401, 5, 3, 1, 9, 46}, "Camellia-256/GCM");
      case 0x8E90B5:
         return if_match(oid, {1, 2, 840, 113533, 7, 66, 10}, "CAST-128/CBC");
      case 0x8E90BA:
         return if_match(oid, {1, 2, 840, 113533, 7, 66, 15}, "KeyWrap.CAST-128");
      case 0x951F58:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 3}, "McEliece");
      case 0x951F5A:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 5}, "XMSS-draft6");
      case 0x951F5D:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 8}, "XMSS-draft12");
      case 0x951F62:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 13}, "HSS-LMS-Private-Key");
      case 0x952158:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 3, 1}, "Serpent/CBC");
      case 0x952159:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 3, 2}, "Threefish-512/CBC");
      case 0x95215A:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 3, 3}, "Twofish/CBC");
      case 0x9521BC:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 3, 101}, "Serpent/GCM");
      case 0x9521BD:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 3, 102}, "Twofish/GCM");
      case 0x952259:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 4, 1}, "numsp256d1");
      case 0x95225A:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 4, 2}, "numsp384d1");
      case 0x95225B:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 4, 3}, "numsp512d1");
      case 0x95ED64:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 1, 2}, "AES-128/CBC");
      case 0x95ED67:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 1, 5}, "KeyWrap.AES-128");
      case 0x95ED68:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 1, 6}, "AES-128/GCM");
      case 0x95ED69:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 1, 7}, "AES-128/CCM");
      case 0x95ED78:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 1, 22}, "AES-192/CBC");
      case 0x95ED7B:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 1, 25}, "KeyWrap.AES-192");
      case 0x95ED7C:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 1, 26}, "AES-192/GCM");
      case 0x95ED7D:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 1, 27}, "AES-192/CCM");
      case 0x95ED8C:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 1, 42}, "AES-256/CBC");
      case 0x95ED8F:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 1, 45}, "KeyWrap.AES-256");
      case 0x95ED90:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 1, 46}, "AES-256/GCM");
      case 0x95ED91:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 1, 47}, "AES-256/CCM");
      case 0x95EE64:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 2, 1}, "SHA-256");
      case 0x95EE65:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 2, 2}, "SHA-384");
      case 0x95EE66:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 2, 3}, "SHA-512");
      case 0x95EE67:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 2, 4}, "SHA-224");
      case 0x95EE69:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 2, 6}, "SHA-512-256");
      case 0x95EE6A:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 2, 7}, "SHA-3(224)");
      case 0x95EE6B:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 2, 8}, "SHA-3(256)");
      case 0x95EE6C:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 2, 9}, "SHA-3(384)");
      case 0x95EE6D:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 2, 10}, "SHA-3(512)");
      case 0x95EE6E:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 2, 11}, "SHAKE-128");
      case 0x95EE6F:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 2, 12}, "SHAKE-256");
      case 0x95EF65:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 3, 1}, "DSA/SHA-224");
      case 0x95EF66:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 3, 2}, "DSA/SHA-256");
      case 0x95EF67:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 3, 3}, "DSA/SHA-384");
      case 0x95EF68:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 3, 4}, "DSA/SHA-512");
      case 0x95EF69:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 3, 5}, "DSA/SHA-3(224)");
      case 0x95EF6A:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 3, 6}, "DSA/SHA-3(256)");
      case 0x95EF6B:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 3, 7}, "DSA/SHA-3(384)");
      case 0x95EF6C:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 3, 8}, "DSA/SHA-3(512)");
      case 0x95EF6D:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 3, 9}, "ECDSA/SHA-3(224)");
      case 0x95EF6E:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 3, 10}, "ECDSA/SHA-3(256)");
      case 0x95EF6F:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 3, 11}, "ECDSA/SHA-3(384)");
      case 0x95EF70:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 3, 12}, "ECDSA/SHA-3(512)");
      case 0x95EF71:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 3, 13}, "RSA/PKCS1v15(SHA-3(224))");
      case 0x95EF72:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 3, 14}, "RSA/PKCS1v15(SHA-3(256))");
      case 0x95EF73:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 3, 15}, "RSA/PKCS1v15(SHA-3(384))");
      case 0x95EF74:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 3, 16}, "RSA/PKCS1v15(SHA-3(512))");
      case 0x95EF75:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 3, 17}, "ML-DSA-4x4");
      case 0x95EF76:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 3, 18}, "ML-DSA-6x5");
      case 0x95EF77:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 3, 19}, "ML-DSA-8x7");
      case 0x95EF78:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 3, 20}, "SLH-DSA-SHA2-128s");
      case 0x95EF79:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 3, 21}, "SLH-DSA-SHA2-128f");
      case 0x95EF7A:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 3, 22}, "SLH-DSA-SHA2-192s");
      case 0x95EF7B:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 3, 23}, "SLH-DSA-SHA2-192f");
      case 0x95EF7C:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 3, 24}, "SLH-DSA-SHA2-256s");
      case 0x95EF7D:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 3, 25}, "SLH-DSA-SHA2-256f");
      case 0x95EF7E:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 3, 26}, "SLH-DSA-SHAKE-128s");
      case 0x95EF7F:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 3, 27}, "SLH-DSA-SHAKE-128f");
      case 0x95EF80:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 3, 28}, "SLH-DSA-SHAKE-192s");
      case 0x95EF81:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 3, 29}, "SLH-DSA-SHAKE-192f");
      case 0x95EF82:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 3, 30}, "SLH-DSA-SHAKE-256s");
      case 0x95EF83:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 3, 31}, "SLH-DSA-SHAKE-256f");
      case 0x95F066:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 4, 1}, "ML-KEM-512");
      case 0x95F067:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 4, 2}, "ML-KEM-768");
      case 0x95F068:
         return if_match(oid, {2, 16, 840, 1, 101, 3, 4, 4, 3}, "ML-KEM-1024");
      case 0x9C113B:
         return if_match(oid, {0, 4, 0, 127, 0, 15, 1, 1, 13, 0}, "XMSS");
      case 0xA0692D:
         return if_match(oid, {1, 2, 643, 7, 1, 2, 1, 1, 1}, "gost_256A");
      case 0xA0692E:
         return if_match(oid, {1, 2, 643, 7, 1, 2, 1, 1, 2}, "gost_256B");
      case 0xA06A2E:
         return if_match(oid, {1, 2, 643, 7, 1, 2, 1, 2, 1}, "gost_512A");
      case 0xA06A2F:
         return if_match(oid, {1, 2, 643, 7, 1, 2, 1, 2, 2}, "gost_512B");
      case 0xA8BC2A:
         return if_match(oid, {1, 3, 132, 0, 8}, "secp160r1");
      case 0xA8BC2B:
         return if_match(oid, {1, 3, 132, 0, 9}, "secp160k1");
      case 0xA8BC2C:
         return if_match(oid, {1, 3, 132, 0, 10}, "secp256k1");
      case 0xA8BC40:
         return if_match(oid, {1, 3, 132, 0, 30}, "secp160r2");
      case 0xA8BC41:
         return if_match(oid, {1, 3, 132, 0, 31}, "secp192k1");
      case 0xA8BC42:
         return if_match(oid, {1, 3, 132, 0, 32}, "secp224k1");
      case 0xA8BC43:
         return if_match(oid, {1, 3, 132, 0, 33}, "secp224r1");
      case 0xA8BC44:
         return if_match(oid, {1, 3, 132, 0, 34}, "secp384r1");
      case 0xA8BC45:
         return if_match(oid, {1, 3, 132, 0, 35}, "secp521r1");
      case 0xA8BD2F:
         return if_match(oid, {1, 3, 132, 1, 12}, "ECDH");
      case 0xA91D85:
         return if_match(oid, {1, 2, 643, 100, 1}, "GOST.OGRN");
      case 0xA91DF3:
         return if_match(oid, {1, 2, 643, 100, 111}, "GOST.SubjectSigningTool");
      case 0xA91DF4:
         return if_match(oid, {1, 2, 643, 100, 112}, "GOST.IssuerSigningTool");
      case 0xB47A5C:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 6, 1}, "GOST-34.10-2012-256/SHA-256");
      case 0xB47B5D:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 7, 1}, "Kyber-512-r3");
      case 0xB47B5E:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 7, 2}, "Kyber-768-r3");
      case 0xB47B5F:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 7, 3}, "Kyber-1024-r3");
      case 0xB47D5F:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 9, 1}, "Dilithium-4x4-r3");
      case 0xB47D60:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 9, 2}, "Dilithium-6x5-r3");
      case 0xB47D61:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 9, 3}, "Dilithium-8x7-r3");
      case 0xB47E60:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 10, 1}, "Dilithium-4x4-AES-r3");
      case 0xB47E61:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 10, 2}, "Dilithium-6x5-AES-r3");
      case 0xB47E62:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 10, 3}, "Dilithium-8x7-AES-r3");
      case 0xB47F61:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 11, 1}, "Kyber-512-90s-r3");
      case 0xB47F62:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 11, 2}, "Kyber-768-90s-r3");
      case 0xB47F63:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 11, 3}, "Kyber-1024-90s-r3");
      case 0xB48264:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 14, 1}, "FrodoKEM-640-SHAKE");
      case 0xB48265:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 14, 2}, "FrodoKEM-976-SHAKE");
      case 0xB48266:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 14, 3}, "FrodoKEM-1344-SHAKE");
      case 0xB48365:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 15, 1}, "FrodoKEM-640-AES");
      case 0xB48366:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 15, 2}, "FrodoKEM-976-AES");
      case 0xB48367:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 15, 3}, "FrodoKEM-1344-AES");
      case 0xB48466:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 16, 1}, "eFrodoKEM-640-SHAKE");
      case 0xB48467:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 16, 2}, "eFrodoKEM-976-SHAKE");
      case 0xB48468:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 16, 3}, "eFrodoKEM-1344-SHAKE");
      case 0xB48567:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 17, 1}, "eFrodoKEM-640-AES");
      case 0xB48568:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 17, 2}, "eFrodoKEM-976-AES");
      case 0xB48569:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 17, 3}, "eFrodoKEM-1344-AES");
      case 0xB48668:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 18, 1}, "ClassicMcEliece_6688128pc");
      case 0xB48669:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 18, 2}, "ClassicMcEliece_6688128pcf");
      case 0xB4866A:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 18, 3}, "ClassicMcEliece_6960119pc");
      case 0xB4866B:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 18, 4}, "ClassicMcEliece_6960119pcf");
      case 0xB4866C:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 18, 5}, "ClassicMcEliece_8192128pc");
      case 0xB4866D:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 1, 18, 6}, "ClassicMcEliece_8192128pcf");
      case 0xB67A5A:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 3, 2, 1}, "AES-128/OCB");
      case 0xB67A5B:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 3, 2, 2}, "AES-192/OCB");
      case 0xB67A5C:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 3, 2, 3}, "AES-256/OCB");
      case 0xB67A5D:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 3, 2, 4}, "Serpent/OCB");
      case 0xB67A5E:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 3, 2, 5}, "Twofish/OCB");
      case 0xB67A5F:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 3, 2, 6}, "Camellia-128/OCB");
      case 0xB67A60:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 3, 2, 7}, "Camellia-192/OCB");
      case 0xB67A61:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 3, 2, 8}, "Camellia-256/OCB");
      case 0xB67C5C:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 3, 4, 1}, "AES-128/SIV");
      case 0xB67C5D:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 3, 4, 2}, "AES-192/SIV");
      case 0xB67C5E:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 3, 4, 3}, "AES-256/SIV");
      case 0xB67C5F:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 3, 4, 4}, "Serpent/SIV");
      case 0xB67C60:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 3, 4, 5}, "Twofish/SIV");
      case 0xB67C61:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 3, 4, 6}, "Camellia-128/SIV");
      case 0xB67C62:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 3, 4, 7}, "Camellia-192/SIV");
      case 0xB67C63:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 3, 4, 8}, "Camellia-256/SIV");
      case 0xB67C64:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 25258, 3, 4, 9}, "SM4/SIV");
      case 0xB87375:
         return if_match(oid, {1, 2, 840, 113549, 1, 1, 1}, "RSA");
      case 0xB87376:
         return if_match(oid, {1, 2, 840, 113549, 1, 1, 2}, "RSA/PKCS1v15(MD2)");
      case 0xB87378:
         return if_match(oid, {1, 2, 840, 113549, 1, 1, 4}, "RSA/PKCS1v15(MD5)");
      case 0xB87379:
         return if_match(oid, {1, 2, 840, 113549, 1, 1, 5}, "RSA/PKCS1v15(SHA-1)");
      case 0xB8737B:
         return if_match(oid, {1, 2, 840, 113549, 1, 1, 7}, "RSA/OAEP");
      case 0xB8737C:
         return if_match(oid, {1, 2, 840, 113549, 1, 1, 8}, "MGF1");
      case 0xB8737E:
         return if_match(oid, {1, 2, 840, 113549, 1, 1, 10}, "RSA/PSS");
      case 0xB8737F:
         return if_match(oid, {1, 2, 840, 113549, 1, 1, 11}, "RSA/PKCS1v15(SHA-256)");
      case 0xB87380:
         return if_match(oid, {1, 2, 840, 113549, 1, 1, 12}, "RSA/PKCS1v15(SHA-384)");
      case 0xB87381:
         return if_match(oid, {1, 2, 840, 113549, 1, 1, 13}, "RSA/PKCS1v15(SHA-512)");
      case 0xB87382:
         return if_match(oid, {1, 2, 840, 113549, 1, 1, 14}, "RSA/PKCS1v15(SHA-224)");
      case 0xB87384:
         return if_match(oid, {1, 2, 840, 113549, 1, 1, 16}, "RSA/PKCS1v15(SHA-512-256)");
      case 0xB87784:
         return if_match(oid, {1, 2, 840, 113549, 1, 5, 12}, "PKCS5.PBKDF2");
      case 0xB87785:
         return if_match(oid, {1, 2, 840, 113549, 1, 5, 13}, "PBE-PKCS5v20");
      case 0xB87B7D:
         return if_match(oid, {1, 2, 840, 113549, 1, 9, 1}, "PKCS9.EmailAddress");
      case 0xB87B7E:
         return if_match(oid, {1, 2, 840, 113549, 1, 9, 2}, "PKCS9.UnstructuredName");
      case 0xB87B7F:
         return if_match(oid, {1, 2, 840, 113549, 1, 9, 3}, "PKCS9.ContentType");
      case 0xB87B80:
         return if_match(oid, {1, 2, 840, 113549, 1, 9, 4}, "PKCS9.MessageDigest");
      case 0xB87B83:
         return if_match(oid, {1, 2, 840, 113549, 1, 9, 7}, "PKCS9.ChallengePassword");
      case 0xB87B8A:
         return if_match(oid, {1, 2, 840, 113549, 1, 9, 14}, "PKCS9.ExtensionRequest");
      case 0xB90079:
         return if_match(oid, {1, 2, 840, 113549, 2, 5}, "MD5");
      case 0xB9007B:
         return if_match(oid, {1, 2, 840, 113549, 2, 7}, "HMAC(SHA-1)");
      case 0xB9007C:
         return if_match(oid, {1, 2, 840, 113549, 2, 8}, "HMAC(SHA-224)");
      case 0xB9007D:
         return if_match(oid, {1, 2, 840, 113549, 2, 9}, "HMAC(SHA-256)");
      case 0xB9007E:
         return if_match(oid, {1, 2, 840, 113549, 2, 10}, "HMAC(SHA-384)");
      case 0xB9007F:
         return if_match(oid, {1, 2, 840, 113549, 2, 11}, "HMAC(SHA-512)");
      case 0xB90081:
         return if_match(oid, {1, 2, 840, 113549, 2, 13}, "HMAC(SHA-512-256)");
      case 0xB9017C:
         return if_match(oid, {1, 2, 840, 113549, 3, 7}, "TripleDES/CBC");
      case 0xC16C79:
         return if_match(oid, {1, 2, 156, 10197, 1, 104, 2}, "SM4/CBC");
      case 0xC16C7F:
         return if_match(oid, {1, 2, 156, 10197, 1, 104, 8}, "SM4/GCM");
      case 0xC16CDB:
         return if_match(oid, {1, 2, 156, 10197, 1, 104, 100}, "SM4/OCB");
      case 0xC2323D:
         return if_match(oid, {1, 2, 156, 10197, 1, 301, 1}, "SM2");
      case 0xC2323E:
         return if_match(oid, {1, 2, 156, 10197, 1, 301, 2}, "SM2_Kex");
      case 0xC2323F:
         return if_match(oid, {1, 2, 156, 10197, 1, 301, 3}, "SM2_Enc");
      case 0xC72700:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 11591, 4, 11}, "Scrypt");
      case 0xC73201:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 11591, 15, 1}, "OpenPGP.Ed25519");
      case 0xC809A8:
         return if_match(oid, {1, 2, 643, 3, 131, 1, 1}, "GOST.INN");
      case 0xCBF63C:
         return if_match(oid, {1, 2, 156, 10197, 1, 301}, "sm2p256v1");
      case 0xCBF6A0:
         return if_match(oid, {1, 2, 156, 10197, 1, 401}, "SM3");
      case 0xCBF704:
         return if_match(oid, {1, 2, 156, 10197, 1, 501}, "SM2_Sig/SM3");
      case 0xCBF707:
         return if_match(oid, {1, 2, 156, 10197, 1, 504}, "RSA/PKCS1v15(SM3)");
      case 0xDED7DD:
         return if_match(oid, {1, 2, 250, 1, 223, 101, 256, 1}, "frp256v1");
      case 0xE8C2CB:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 22554, 5, 1, 1}, "ClassicMcEliece_348864");
      case 0xE8C2CC:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 22554, 5, 1, 2}, "ClassicMcEliece_348864f");
      case 0xE8C2CD:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 22554, 5, 1, 3}, "ClassicMcEliece_460896");
      case 0xE8C2CE:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 22554, 5, 1, 4}, "ClassicMcEliece_460896f");
      case 0xE8C2CF:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 22554, 5, 1, 5}, "ClassicMcEliece_6688128");
      case 0xE8C2D0:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 22554, 5, 1, 6}, "ClassicMcEliece_6688128f");
      case 0xE8C2D1:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 22554, 5, 1, 7}, "ClassicMcEliece_6960119");
      case 0xE8C2D2:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 22554, 5, 1, 8}, "ClassicMcEliece_6960119f");
      case 0xE8C2D3:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 22554, 5, 1, 9}, "ClassicMcEliece_8192128");
      case 0xE8C2D4:
         return if_match(oid, {1, 3, 6, 1, 4, 1, 22554, 5, 1, 10}, "ClassicMcEliece_8192128f");
      case 0xEEFDCB:
         return if_match(oid, {1, 0, 14888, 3, 0, 5}, "ECKCDSA");
      case 0xF49CE8:
         return if_match(oid, {1, 3, 6, 1, 5, 5, 7, 48, 1, 1}, "PKIX.OCSP.BasicResponse");
      case 0xF49CEC:
         return if_match(oid, {1, 3, 6, 1, 5, 5, 7, 48, 1, 5}, "PKIX.OCSP.NoCheck");
      case 0xFE30D2:
         return if_match(oid, {1, 3, 36, 3, 3, 2, 5, 2, 1}, "ECGDSA");
      case 0xFE32D4:
         return if_match(oid, {1, 3, 36, 3, 3, 2, 5, 4, 1}, "ECGDSA/RIPEMD-160");
      case 0xFE32D5:
         return if_match(oid, {1, 3, 36, 3, 3, 2, 5, 4, 2}, "ECGDSA/SHA-1");
      case 0xFE32D6:
         return if_match(oid, {1, 3, 36, 3, 3, 2, 5, 4, 3}, "ECGDSA/SHA-224");
      case 0xFE32D7:
         return if_match(oid, {1, 3, 36, 3, 3, 2, 5, 4, 4}, "ECGDSA/SHA-256");
      case 0xFE32D8:
         return if_match(oid, {1, 3, 36, 3, 3, 2, 5, 4, 5}, "ECGDSA/SHA-384");
      case 0xFE32D9:
         return if_match(oid, {1, 3, 36, 3, 3, 2, 5, 4, 6}, "ECGDSA/SHA-512");
      default:
         return {};
   }
   // clang-format on
}

//static
std::optional<OID> OID_Map::lookup_static_oid_name(std::string_view req) {
   const uint32_t hc = hash_oid_name(req);

   // clang-format off
   switch(hc) {

      case 0x00044C:
         return if_match(req, "ML-DSA-6x5", {2, 16, 840, 1, 101, 3, 4, 3, 18});
      case 0x01ACF3:
         return if_match(req, "ClassicMcEliece_6960119pcf", {1, 3, 6, 1, 4, 1, 25258, 1, 18, 4});
      case 0x01F080:
         return if_match(req, "ML-DSA-8x7", {2, 16, 840, 1, 101, 3, 4, 3, 19});
      case 0x022DFD:
         return if_match(req, "ECKCDSA", {1, 0, 14888, 3, 0, 5});
      case 0x023426:
         return if_match(req, "DH", {1, 2, 840, 10046, 2, 1});
      case 0x0235A7:
         return if_match(req, "RSA/PKCS1v15(SHA-1)", {1, 2, 840, 113549, 1, 1, 5});
      case 0x0359C1:
         return if_match(req, "SLH-DSA-SHAKE-256f", {2, 16, 840, 1, 101, 3, 4, 3, 31});
      case 0x0359CE:
         return if_match(req, "SLH-DSA-SHAKE-256s", {2, 16, 840, 1, 101, 3, 4, 3, 30});
      case 0x039345:
         return if_match(req, "Dilithium-8x7-r3", {1, 3, 6, 1, 4, 1, 25258, 1, 9, 3});
      case 0x051BAF:
         return if_match(req, "X509v3.ExtendedKeyUsage", {2, 5, 29, 37});
      case 0x0604E7:
         return if_match(req, "GOST.SubjectSigningTool", {1, 2, 643, 100, 111});
      case 0x06A7B7:
         return if_match(req, "Certificate Comment", {2, 16, 840, 1, 113730, 1, 13});
      case 0x0832C6:
         return if_match(req, "FrodoKEM-976-AES", {1, 3, 6, 1, 4, 1, 25258, 1, 15, 2});
      case 0x08981E:
         return if_match(req, "GOST-34.10-2012-256/SHA-256", {1, 3, 6, 1, 4, 1, 25258, 1, 6, 1});
      case 0x0A841E:
         return if_match(req, "ML-KEM-1024", {2, 16, 840, 1, 101, 3, 4, 4, 3});
      case 0x0CFB49:
         return if_match(req, "sm2p256v1", {1, 2, 156, 10197, 1, 301});
      case 0x0DCD52:
         return if_match(req, "DSA/SHA-1", {1, 2, 840, 10040, 4, 3});
      case 0x0F2EE9:
         return if_match(req, "SLH-DSA-SHAKE-128f", {2, 16, 840, 1, 101, 3, 4, 3, 27});
      case 0x0F2EF6:
         return if_match(req, "SLH-DSA-SHAKE-128s", {2, 16, 840, 1, 101, 3, 4, 3, 26});
      case 0x0F64A4:
         return if_match(req, "FrodoKEM-640-AES", {1, 3, 6, 1, 4, 1, 25258, 1, 15, 1});
      case 0x1073A3:
         return if_match(req, "X520.Country", {2, 5, 4, 6});
      case 0x10ED59:
         return if_match(req, "Camellia-128/CBC", {1, 2, 392, 200011, 61, 1, 1, 1, 2});
      case 0x1285C6:
         return if_match(req, "SphincsPlus-sha2-192s-r3.1", {1, 3, 6, 1, 4, 1, 25258, 1, 12, 2, 3});
      case 0x14C6C2:
         return if_match(req, "Camellia-128/GCM", {0, 3, 4401, 5, 3, 1, 9, 6});
      case 0x15C990:
         return if_match(req, "Microsoft SmartcardLogon", {1, 3, 6, 1, 4, 1, 311, 20, 2, 2});
      case 0x15E3B6:
         return if_match(req, "SLH-DSA-SHAKE-192f", {2, 16, 840, 1, 101, 3, 4, 3, 29});
      case 0x15E3C3:
         return if_match(req, "SLH-DSA-SHAKE-192s", {2, 16, 840, 1, 101, 3, 4, 3, 28});
      case 0x1894F9:
         return if_match(req, "SphincsPlus-shake-128f-r3.1", {1, 3, 6, 1, 4, 1, 25258, 1, 12, 1, 2});
      case 0x1A4B73:
         return if_match(req, "Threefish-512/CBC", {1, 3, 6, 1, 4, 1, 25258, 3, 2});
      case 0x1A76CF:
         return if_match(req, "DSA", {1, 2, 840, 10040, 4, 1});
      case 0x1B8B33:
         return if_match(req, "AES-128/CBC", {2, 16, 840, 1, 101, 3, 4, 1, 2});
      case 0x1B8C38:
         return if_match(req, "AES-128/CCM", {2, 16, 840, 1, 101, 3, 4, 1, 7});
      case 0x1C777F:
         return if_match(req, "Camellia-128/OCB", {1, 3, 6, 1, 4, 1, 25258, 3, 2, 6});
      case 0x1E6334:
         return if_match(req, "ECDSA/SHA-3(512)", {2, 16, 840, 1, 101, 3, 4, 3, 12});
      case 0x1F649C:
         return if_match(req, "AES-128/GCM", {2, 16, 840, 1, 101, 3, 4, 1, 6});
      case 0x2055D9:
         return if_match(req, "Camellia-128/SIV", {1, 3, 6, 1, 4, 1, 25258, 3, 4, 6});
      case 0x20ED25:
         return if_match(req, "Scrypt", {1, 3, 6, 1, 4, 1, 11591, 4, 11});
      case 0x230EEF:
         return if_match(req, "MD5", {1, 2, 840, 113549, 2, 5});
      case 0x237E02:
         return if_match(req, "X509v3.NameConstraints", {2, 5, 29, 30});
      case 0x2486E6:
         return if_match(req, "secp224k1", {1, 3, 132, 0, 32});
      case 0x248DC3:
         return if_match(req, "secp224r1", {1, 3, 132, 0, 33});
      case 0x25E019:
         return if_match(req, "GOST-34.10/GOST-R-34.11-94", {1, 2, 643, 2, 2, 3});
      case 0x266BB5:
         return if_match(req, "Kyber-512-90s-r3", {1, 3, 6, 1, 4, 1, 25258, 1, 11, 1});
      case 0x271559:
         return if_match(req, "AES-128/OCB", {1, 3, 6, 1, 4, 1, 25258, 3, 2, 1});
      case 0x2795D8:
         return if_match(req, "secp192k1", {1, 3, 132, 0, 31});
      case 0x279CB5:
         return if_match(req, "secp192r1", {1, 2, 840, 10045, 3, 1, 1});
      case 0x27EC2D:
         return if_match(req, "RSA", {1, 2, 840, 113549, 1, 1, 1});
      case 0x280B77:
         return if_match(req, "ClassicMcEliece_460896", {1, 3, 6, 1, 4, 1, 22554, 5, 1, 3});
      case 0x28DC55:
         return if_match(req, "SM2", {1, 2, 156, 10197, 1, 301, 1});
      case 0x28DC56:
         return if_match(req, "SM3", {1, 2, 156, 10197, 1, 401});
      case 0x298F1D:
         return if_match(req, "PKIX.TNAuthList", {1, 3, 6, 1, 5, 5, 7, 1, 26});
      case 0x2A970E:
         return if_match(req, "ECDSA/SHA-1", {1, 2, 840, 10045, 4, 1});
      case 0x2AF3B3:
         return if_match(req, "AES-128/SIV", {1, 3, 6, 1, 4, 1, 25258, 3, 4, 1});
      case 0x2AF8FC:
         return if_match(req, "brainpool320r1", {1, 3, 36, 3, 3, 2, 8, 1, 1, 9});
      case 0x2CF12F:
         return if_match(req, "X509v3.ReasonCode", {2, 5, 29, 21});
      case 0x2F7A90:
         return if_match(req, "RSA/OAEP", {1, 2, 840, 113549, 1, 1, 7});
      case 0x2FE5A6:
         return if_match(req, "X520.GenerationalQualifier", {2, 5, 4, 44});
      case 0x321542:
         return if_match(req, "ECGDSA/SHA-1", {1, 3, 36, 3, 3, 2, 5, 4, 2});
      case 0x32C06A:
         return if_match(req, "X509v3.SubjectAlternativeName", {2, 5, 29, 17});
      case 0x339344:
         return if_match(req, "SM4/CBC", {1, 2, 156, 10197, 1, 104, 2});
      case 0x34BB5F:
         return if_match(req, "GOST-34.10-2012-256", {1, 2, 643, 7, 1, 1, 1, 1});
      case 0x376CAD:
         return if_match(req, "SM4/GCM", {1, 2, 156, 10197, 1, 104, 8});
      case 0x3799BA:
         return if_match(req, "GOST-34.10-2012-512", {1, 2, 643, 7, 1, 1, 1, 2});
      case 0x3850B1:
         return if_match(req, "ClassicMcEliece_6688128f", {1, 3, 6, 1, 4, 1, 22554, 5, 1, 6});
      case 0x3964B1:
         return if_match(req, "X509v3.CRLDistributionPoints", {2, 5, 29, 31});
      case 0x3B3720:
         return if_match(req, "HMAC(SHA-512)", {1, 2, 840, 113549, 2, 11});
      case 0x3B388F:
         return if_match(req, "FrodoKEM-976-SHAKE", {1, 3, 6, 1, 4, 1, 25258, 1, 14, 2});
      case 0x3CA748:
         return if_match(req, "SphincsPlus-shake-128s-r3.1", {1, 3, 6, 1, 4, 1, 25258, 1, 12, 1, 1});
      case 0x3CF1AB:
         return if_match(req, "PKCS9.ChallengePassword", {1, 2, 840, 113549, 1, 9, 7});
      case 0x3F1D6A:
         return if_match(req, "SM4/OCB", {1, 2, 156, 10197, 1, 104, 100});
      case 0x426CFA:
         return if_match(req, "eFrodoKEM-1344-SHAKE", {1, 3, 6, 1, 4, 1, 25258, 1, 16, 3});
      case 0x428414:
         return if_match(req, "X448", {1, 3, 101, 111});
      case 0x428AD3:
         return if_match(req, "ECDSA/SHA-3(384)", {2, 16, 840, 1, 101, 3, 4, 3, 11});
      case 0x42FBC4:
         return if_match(req, "SM4/SIV", {1, 3, 6, 1, 4, 1, 25258, 3, 4, 9});
      case 0x432A11:
         return if_match(req, "eFrodoKEM-640-SHAKE", {1, 3, 6, 1, 4, 1, 25258, 1, 16, 1});
      case 0x449390:
         return if_match(req, "ClassicMcEliece_6960119f", {1, 3, 6, 1, 4, 1, 22554, 5, 1, 8});
      case 0x449638:
         return if_match(req, "Microsoft UPN", {1, 3, 6, 1, 4, 1, 311, 20, 2, 3});
      case 0x450DB4:
         return if_match(req, "RSA/PKCS1v15(SM3)", {1, 2, 156, 10197, 1, 504});
      case 0x4B7BBA:
         return if_match(req, "ECDSA/SHA-3(224)", {2, 16, 840, 1, 101, 3, 4, 3, 9});
      case 0x4B8668:
         return if_match(req, "SM2_Enc", {1, 2, 156, 10197, 1, 301, 3});
      case 0x4BFB88:
         return if_match(req, "SphincsPlus-shake-192f-r3.1", {1, 3, 6, 1, 4, 1, 25258, 1, 12, 1, 4});
      case 0x4C5734:
         return if_match(req, "OpenPGP.Curve25519", {1, 3, 6, 1, 4, 1, 3029, 1, 5, 1});
      case 0x4D83CA:
         return if_match(req, "PKIX.AuthorityInformationAccess", {1, 3, 6, 1, 5, 5, 7, 1, 1});
      case 0x4DEEE8:
         return if_match(req, "X509v3.IssuerAlternativeName", {2, 5, 29, 18});
      case 0x4E5FFB:
         return if_match(req, "ECDSA/SHA-3(256)", {2, 16, 840, 1, 101, 3, 4, 3, 10});
      case 0x4E7E8F:
         return if_match(req, "RSA/PKCS1v15(SHA-3(512))", {2, 16, 840, 1, 101, 3, 4, 3, 16});
      case 0x4FDAD7:
         return if_match(req, "X520.Pseudonym", {2, 5, 4, 65});
      case 0x5127D3:
         return if_match(req, "PKIX.OCSP.BasicResponse", {1, 3, 6, 1, 5, 5, 7, 48, 1, 1});
      case 0x514240:
         return if_match(req, "SM2_Kex", {1, 2, 156, 10197, 1, 301, 2});
      case 0x51CA1D:
         return if_match(req, "secp160k1", {1, 3, 132, 0, 9});
      case 0x51D0FA:
         return if_match(req, "secp160r1", {1, 3, 132, 0, 8});
      case 0x51D0FB:
         return if_match(req, "secp160r2", {1, 3, 132, 0, 30});
      case 0x531FF6:
         return if_match(req, "RSA/PKCS1v15(SHA-512-256)", {1, 2, 840, 113549, 1, 1, 16});
      case 0x54BC71:
         return if_match(req, "Serpent/CBC", {1, 3, 6, 1, 4, 1, 25258, 3, 1});
      case 0x551D36:
         return if_match(req, "PKIX.AutonomousSysIds", {1, 3, 6, 1, 5, 5, 7, 1, 8});
      case 0x552907:
         return if_match(req, "Streebog-256", {1, 2, 643, 7, 1, 1, 2, 2});
      case 0x556EDE:
         return if_match(req, "PKCS9.EmailAddress", {1, 2, 840, 113549, 1, 9, 1});
      case 0x57E96A:
         return if_match(req, "PKCS9.ExtensionRequest", {1, 2, 840, 113549, 1, 9, 14});
      case 0x580762:
         return if_match(req, "Streebog-512", {1, 2, 643, 7, 1, 1, 2, 3});
      case 0x5895DA:
         return if_match(req, "Serpent/GCM", {1, 3, 6, 1, 4, 1, 25258, 3, 101});
      case 0x59685E:
         return if_match(req, "SphincsPlus-haraka-256f-r3.1", {1, 3, 6, 1, 4, 1, 25258, 1, 12, 3, 6});
      case 0x5AAB05:
         return if_match(req, "XMSS", {0, 4, 0, 127, 0, 15, 1, 1, 13, 0});
      case 0x5ACAB0:
         return if_match(req, "FrodoKEM-1344-SHAKE", {1, 3, 6, 1, 4, 1, 25258, 1, 14, 3});
      case 0x5B55AC:
         return if_match(req, "RSA/PKCS1v15(SHA-3(256))", {2, 16, 840, 1, 101, 3, 4, 3, 14});
      case 0x5F5EBF:
         return if_match(req, "HMAC(SHA-384)", {1, 2, 840, 113549, 2, 10});
      case 0x6016EF:
         return if_match(req, "ClassicMcEliece_348864", {1, 3, 6, 1, 4, 1, 22554, 5, 1, 1});
      case 0x604697:
         return if_match(req, "Serpent/OCB", {1, 3, 6, 1, 4, 1, 25258, 3, 2, 4});
      case 0x605B46:
         return if_match(req, "secp384r1", {1, 3, 132, 0, 34});
      case 0x623622:
         return if_match(req, "ECGDSA/RIPEMD-160", {1, 3, 36, 3, 3, 2, 5, 4, 1});
      case 0x63A71B:
         return if_match(req, "SHA-1", {1, 3, 14, 3, 2, 26});
      case 0x63B78D:
         return if_match(req, "brainpool512r1", {1, 3, 36, 3, 3, 2, 8, 1, 1, 13});
      case 0x640EE2:
         return if_match(req, "PKIX.IPsecTunnel", {1, 3, 6, 1, 5, 5, 7, 3, 6});
      case 0x641D81:
         return if_match(req, "ClassicMcEliece_8192128pc", {1, 3, 6, 1, 4, 1, 25258, 1, 18, 5});
      case 0x6424F1:
         return if_match(req, "Serpent/SIV", {1, 3, 6, 1, 4, 1, 25258, 3, 4, 4});
      case 0x6541F1:
         return if_match(req, "X509v3.PolicyConstraints", {2, 5, 29, 36});
      case 0x66EE7D:
         return if_match(req, "PKIX.EmailProtection", {1, 3, 6, 1, 5, 5, 7, 3, 4});
      case 0x671622:
         return if_match(req, "X520.CommonName", {2, 5, 4, 3});
      case 0x684FA6:
         return if_match(req, "HMAC(SHA-224)", {1, 2, 840, 113549, 2, 8});
      case 0x687792:
         return if_match(req, "ECDH", {1, 3, 132, 1, 12});
      case 0x698DAE:
         return if_match(req, "HMAC(SHA-512-256)", {1, 2, 840, 113549, 2, 13});
      case 0x6AF5CE:
         return if_match(req, "ClassicMcEliece_348864f", {1, 3, 6, 1, 4, 1, 22554, 5, 1, 2});
      case 0x6B33E7:
         return if_match(req, "HMAC(SHA-256)", {1, 2, 840, 113549, 2, 9});
      case 0x6BD4BA:
         return if_match(req, "RSA/PSS", {1, 2, 840, 113549, 1, 1, 10});
      case 0x6DD3C0:
         return if_match(req, "GOST-34.10-2012-512/Streebog-512", {1, 2, 643, 7, 1, 1, 3, 3});
      case 0x6E77E8:
         return if_match(req, "DSA/SHA-3(512)", {2, 16, 840, 1, 101, 3, 4, 3, 8});
      case 0x6EA392:
         return if_match(req, "PKCS9.ContentType", {1, 2, 840, 113549, 1, 9, 3});
      case 0x6F33B1:
         return if_match(req, "X520.Initials", {2, 5, 4, 43});
      case 0x700DD7:
         return if_match(req, "SphincsPlus-shake-192s-r3.1", {1, 3, 6, 1, 4, 1, 25258, 1, 12, 1, 3});
      case 0x708EAA:
         return if_match(req, "brainpool256r1", {1, 3, 36, 3, 3, 2, 8, 1, 1, 7});
      case 0x73012A:
         return if_match(req, "SEED/CBC", {1, 2, 410, 200004, 1, 4});
      case 0x733A29:
         return if_match(req, "Kyber-1024-90s-r3", {1, 3, 6, 1, 4, 1, 25258, 1, 11, 3});
      case 0x74FB49:
         return if_match(req, "X520.Organization", {2, 5, 4, 10});
      case 0x750788:
         return if_match(req, "X520.StreetAddress", {2, 5, 4, 9});
      case 0x77B726:
         return if_match(req, "ClassicMcEliece_460896f", {1, 3, 6, 1, 4, 1, 22554, 5, 1, 4});
      case 0x7AC630:
         return if_match(req, "SphincsPlus-sha2-256f-r3.1", {1, 3, 6, 1, 4, 1, 25258, 1, 12, 2, 6});
      case 0x7D7AAD:
         return if_match(req, "SphincsPlus-haraka-256s-r3.1", {1, 3, 6, 1, 4, 1, 25258, 1, 12, 3, 5});
      case 0x81F558:
         return if_match(req, "ClassicMcEliece_8192128", {1, 3, 6, 1, 4, 1, 22554, 5, 1, 9});
      case 0x824D5F:
         return if_match(req, "HMAC(SHA-1)", {1, 2, 840, 113549, 2, 7});
      case 0x8589F1:
         return if_match(req, "RSA/PKCS1v15(SHA-3(224))", {2, 16, 840, 1, 101, 3, 4, 3, 13});
      case 0x871090:
         return if_match(req, "Dilithium-4x4-r3", {1, 3, 6, 1, 4, 1, 25258, 1, 9, 1});
      case 0x87BF63:
         return if_match(req, "X509v3.HoldInstructionCode", {2, 5, 29, 23});
      case 0x884D9C:
         return if_match(req, "gost_512A", {1, 2, 643, 7, 1, 2, 1, 2, 1});
      case 0x884D9D:
         return if_match(req, "gost_512B", {1, 2, 643, 7, 1, 2, 1, 2, 2});
      case 0x887C4B:
         return if_match(req, "ClassicMcEliece_6960119", {1, 3, 6, 1, 4, 1, 22554, 5, 1, 7});
      case 0x89C372:
         return if_match(req, "numsp512d1", {1, 3, 6, 1, 4, 1, 25258, 4, 3});
      case 0x8C8874:
         return if_match(req, "PBE-PKCS5v20", {1, 2, 840, 113549, 1, 5, 13});
      case 0x8CDB2C:
         return if_match(req, "ClassicMcEliece_6688128pcf", {1, 3, 6, 1, 4, 1, 25258, 1, 18, 2});
      case 0x8E846B:
         return if_match(req, "McEliece", {1, 3, 6, 1, 4, 1, 25258, 1, 3});
      case 0x8F3FB0:
         return if_match(req, "X509v3.BasicConstraints", {2, 5, 29, 19});
      case 0x8FEFDC:
         return if_match(req, "GOST.OGRN", {1, 2, 643, 100, 1});
      case 0x926F06:
         return if_match(req, "HSS-LMS", {1, 2, 840, 113549, 1, 9, 16, 3, 17});
      case 0x929F87:
         return if_match(req, "DSA/SHA-3(384)", {2, 16, 840, 1, 101, 3, 4, 3, 7});
      case 0x94A6C6:
         return if_match(req, "RSA/PKCS1v15(MD2)", {1, 2, 840, 113549, 1, 1, 2});
      case 0x94A9B7:
         return if_match(req, "RSA/PKCS1v15(MD5)", {1, 2, 840, 113549, 1, 1, 4});
      case 0x96501B:
         return if_match(req, "ECGDSA", {1, 3, 36, 3, 3, 2, 5, 2, 1});
      case 0x969A8F:
         return if_match(req, "numsp256d1", {1, 3, 6, 1, 4, 1, 25258, 4, 1});
      case 0x976FFB:
         return if_match(req, "ECDSA", {1, 2, 840, 10045, 2, 1});
      case 0x98362E:
         return if_match(req, "x962_p239v1", {1, 2, 840, 10045, 3, 1, 4});
      case 0x98362F:
         return if_match(req, "x962_p239v2", {1, 2, 840, 10045, 3, 1, 5});
      case 0x983630:
         return if_match(req, "x962_p239v3", {1, 2, 840, 10045, 3, 1, 6});
      case 0x9926EB:
         return if_match(req, "PKCS5.PBKDF2", {1, 2, 840, 113549, 1, 5, 12});
      case 0x99AF16:
         return if_match(req, "SphincsPlus-haraka-128f-r3.1", {1, 3, 6, 1, 4, 1, 25258, 1, 12, 3, 2});
      case 0x99ED3D:
         return if_match(req, "X520.Locality", {2, 5, 4, 7});
      case 0x9AC2EF:
         return if_match(req, "brainpool224r1", {1, 3, 36, 3, 3, 2, 8, 1, 1, 5});
      case 0x9B906E:
         return if_match(req, "DSA/SHA-3(224)", {2, 16, 840, 1, 101, 3, 4, 3, 5});
      case 0x9BCD4B:
         return if_match(req, "Dilithium-6x5-AES-r3", {1, 3, 6, 1, 4, 1, 25258, 1, 10, 2});
      case 0x9D210F:
         return if_match(req, "X520.GivenName", {2, 5, 4, 42});
      case 0x9DD1E1:
         return if_match(req, "brainpool192r1", {1, 3, 36, 3, 3, 2, 8, 1, 1, 3});
      case 0x9E680D:
         return if_match(req, "KeyWrap.AES-128", {2, 16, 840, 1, 101, 3, 4, 1, 5});
      case 0x9E6EE4:
         return if_match(req, "KeyWrap.AES-192", {2, 16, 840, 1, 101, 3, 4, 1, 25});
      case 0x9E74AF:
         return if_match(req, "DSA/SHA-3(256)", {2, 16, 840, 1, 101, 3, 4, 3, 6});
      case 0x9ED87F:
         return if_match(req, "SphincsPlus-sha2-256s-r3.1", {1, 3, 6, 1, 4, 1, 25258, 1, 12, 2, 5});
      case 0x9EE4CC:
         return if_match(req, "X520.Surname", {2, 5, 4, 4});
      case 0x9F6115:
         return if_match(req, "KeyWrap.AES-256", {2, 16, 840, 1, 101, 3, 4, 1, 45});
      case 0xA0E890:
         return if_match(req, "X520.State", {2, 5, 4, 8});
      case 0xA25A24:
         return if_match(req, "PKIX.ServerAuth", {1, 3, 6, 1, 5, 5, 7, 3, 1});
      case 0xA28AE0:
         return if_match(req, "Ed448", {1, 3, 101, 113});
      case 0xA3F763:
         return if_match(req, "eFrodoKEM-976-SHAKE", {1, 3, 6, 1, 4, 1, 25258, 1, 16, 2});
      case 0xA3F903:
         return if_match(req, "SHAKE-128", {2, 16, 840, 1, 101, 3, 4, 2, 11});
      case 0xA42027:
         return if_match(req, "Dilithium-8x7-AES-r3", {1, 3, 6, 1, 4, 1, 25258, 1, 10, 3});
      case 0xA469CD:
         return if_match(req, "ChaCha20Poly1305", {1, 2, 840, 113549, 1, 9, 16, 3, 18});
      case 0xA47ADD:
         return if_match(req, "Kyber-768-r3", {1, 3, 6, 1, 4, 1, 25258, 1, 7, 2});
      case 0xA4F20B:
         return if_match(req, "SHAKE-256", {2, 16, 840, 1, 101, 3, 4, 2, 12});
      case 0xA52C21:
         return if_match(req, "x962_p192v2", {1, 2, 840, 10045, 3, 1, 2});
      case 0xA52C22:
         return if_match(req, "x962_p192v3", {1, 2, 840, 10045, 3, 1, 3});
      case 0xA5F9AC:
         return if_match(req, "GOST.INN", {1, 2, 643, 3, 131, 1, 1});
      case 0xA7E727:
         return if_match(req, "X520.SerialNumber", {2, 5, 4, 5});
      case 0xAA2496:
         return if_match(req, "X509v3.KeyUsage", {2, 5, 29, 15});
      case 0xACAE87:
         return if_match(req, "ECDSA/SHA-224", {1, 2, 840, 10045, 4, 3, 1});
      case 0xACB17A:
         return if_match(req, "ECDSA/SHA-256", {1, 2, 840, 10045, 4, 3, 2});
      case 0xADAA82:
         return if_match(req, "ECDSA/SHA-384", {1, 2, 840, 10045, 4, 3, 3});
      case 0xAEA53E:
         return if_match(req, "Twofish/CBC", {1, 3, 6, 1, 4, 1, 25258, 3, 3});
      case 0xAF3C97:
         return if_match(req, "ClassicMcEliece_6688128pc", {1, 3, 6, 1, 4, 1, 25258, 1, 18, 1});
      case 0xAF8FD5:
         return if_match(req, "ECDSA/SHA-512", {1, 2, 840, 10045, 4, 3, 4});
      case 0xB0489B:
         return if_match(req, "DSA/SHA-224", {2, 16, 840, 1, 101, 3, 4, 3, 1});
      case 0xB04B8E:
         return if_match(req, "DSA/SHA-256", {2, 16, 840, 1, 101, 3, 4, 3, 2});
      case 0xB05756:
         return if_match(req, "X509v3.CRLIssuingDistributionPoint", {2, 5, 29, 28});
      case 0xB0B899:
         return if_match(req, "SM2_Sig/SM3", {1, 2, 156, 10197, 1, 501});
      case 0xB14496:
         return if_match(req, "DSA/SHA-384", {2, 16, 840, 1, 101, 3, 4, 3, 3});
      case 0xB27EA7:
         return if_match(req, "Twofish/GCM", {1, 3, 6, 1, 4, 1, 25258, 3, 102});
      case 0xB329E9:
         return if_match(req, "DSA/SHA-512", {2, 16, 840, 1, 101, 3, 4, 3, 4});
      case 0xB407A4:
         return if_match(req, "PKIX.OCSPSigning", {1, 3, 6, 1, 5, 5, 7, 3, 9});
      case 0xB4CD3C:
         return if_match(req, "ClassicMcEliece_6960119pc", {1, 3, 6, 1, 4, 1, 25258, 1, 18, 3});
      case 0xB65B9B:
         return if_match(req, "SHA-3(512)", {2, 16, 840, 1, 101, 3, 4, 2, 10});
      case 0xB67821:
         return if_match(req, "PKIX.IpAddrBlocks", {1, 3, 6, 1, 5, 5, 7, 1, 7});
      case 0xB84A63:
         return if_match(req, "gost_256A", {1, 2, 643, 7, 1, 2, 1, 1, 1});
      case 0xB84A64:
         return if_match(req, "gost_256B", {1, 2, 643, 7, 1, 2, 1, 1, 2});
      case 0xBA2F64:
         return if_match(req, "Twofish/OCB", {1, 3, 6, 1, 4, 1, 25258, 3, 2, 5});
      case 0xBA6889:
         return if_match(req, "ECKCDSA/SHA-224", {1, 2, 410, 200004, 1, 100, 4, 4});
      case 0xBA6B7C:
         return if_match(req, "ECKCDSA/SHA-256", {1, 2, 410, 200004, 1, 100, 4, 5});
      case 0xBAEEEB:
         return if_match(req, "RIPEMD-160", {1, 3, 36, 3, 2, 1});
      case 0xBB0CE8:
         return if_match(req, "SphincsPlus-sha2-128f-r3.1", {1, 3, 6, 1, 4, 1, 25258, 1, 12, 2, 2});
      case 0xBB6720:
         return if_match(req, "Ed25519", {1, 3, 101, 112});
      case 0xBC73DE:
         return if_match(req, "ClassicMcEliece_6688128", {1, 3, 6, 1, 4, 1, 22554, 5, 1, 5});
      case 0xBD49E1:
         return if_match(req, "Camellia-256/CBC", {1, 2, 392, 200011, 61, 1, 1, 1, 4});
      case 0xBDC165:
         return if_match(req, "SphincsPlus-haraka-128s-r3.1", {1, 3, 6, 1, 4, 1, 25258, 1, 12, 3, 1});
      case 0xBE0DBE:
         return if_match(req, "Twofish/SIV", {1, 3, 6, 1, 4, 1, 25258, 3, 4, 5});
      case 0xBFB440:
         return if_match(req, "Camellia-192/CBC", {1, 2, 392, 200011, 61, 1, 1, 1, 3});
      case 0xC02313:
         return if_match(req, "X509v3.PrivateKeyUsagePeriod", {2, 5, 29, 16});
      case 0xC1234A:
         return if_match(req, "Camellia-256/GCM", {0, 3, 4401, 5, 3, 1, 9, 46});
      case 0xC15774:
         return if_match(req, "RSA/PKCS1v15(SHA-3(384))", {2, 16, 840, 1, 101, 3, 4, 3, 15});
      case 0xC38DA9:
         return if_match(req, "Camellia-192/GCM", {0, 3, 4401, 5, 3, 1, 9, 26});
      case 0xC3CD83:
         return if_match(req, "X509v3.AuthorityKeyIdentifier", {2, 5, 29, 35});
      case 0xC42200:
         return if_match(req, "Kyber-512-r3", {1, 3, 6, 1, 4, 1, 25258, 1, 7, 1});
      case 0xC45E3E:
         return if_match(req, "X509v3.CertificatePolicies", {2, 5, 29, 32});
      case 0xC4890F:
         return if_match(req, "X509v3.AnyPolicy", {2, 5, 29, 32, 0});
      case 0xC61B14:
         return if_match(req, "DES/CBC", {1, 3, 14, 3, 2, 7});
      case 0xC66F68:
         return if_match(req, "RSA/PKCS1v15(SHA-512)", {1, 2, 840, 113549, 1, 1, 13});
      case 0xC7E7BB:
         return if_match(req, "AES-256/CBC", {2, 16, 840, 1, 101, 3, 4, 1, 42});
      case 0xC7E8C0:
         return if_match(req, "AES-256/CCM", {2, 16, 840, 1, 101, 3, 4, 1, 47});
      case 0xC80626:
         return if_match(req, "brainpool160r1", {1, 3, 36, 3, 3, 2, 8, 1, 1, 1});
      case 0xC8D407:
         return if_match(req, "Camellia-256/OCB", {1, 3, 6, 1, 4, 1, 25258, 3, 2, 8});
      case 0xC8E3FB:
         return if_match(req, "X509v3.CRLNumber", {2, 5, 29, 20});
      case 0xC98502:
         return if_match(req, "CAST-128/CBC", {1, 2, 840, 113533, 7, 66, 10});
      case 0xCA521A:
         return if_match(req, "AES-192/CBC", {2, 16, 840, 1, 101, 3, 4, 1, 22});
      case 0xCA531F:
         return if_match(req, "AES-192/CCM", {2, 16, 840, 1, 101, 3, 4, 1, 27});
      case 0xCA9D85:
         return if_match(req, "X520.DNQualifier", {2, 5, 4, 46});
      case 0xCAEDFF:
         return if_match(req, "RSA/PKCS1v15(RIPEMD-160)", {1, 3, 36, 3, 3, 1, 2});
      case 0xCB3E66:
         return if_match(req, "Camellia-192/OCB", {1, 3, 6, 1, 4, 1, 25258, 3, 2, 7});
      case 0xCB5B1B:
         return if_match(req, "FrodoKEM-1344-AES", {1, 3, 6, 1, 4, 1, 25258, 1, 15, 3});
      case 0xCBC124:
         return if_match(req, "AES-256/GCM", {2, 16, 840, 1, 101, 3, 4, 1, 46});
      case 0xCCACA9:
         return if_match(req, "Dilithium-6x5-r3", {1, 3, 6, 1, 4, 1, 25258, 1, 9, 2});
      case 0xCCB261:
         return if_match(req, "Camellia-256/SIV", {1, 3, 6, 1, 4, 1, 25258, 3, 4, 8});
      case 0xCD15A5:
         return if_match(req, "SphincsPlus-haraka-192f-r3.1", {1, 3, 6, 1, 4, 1, 25258, 1, 12, 3, 4});
      case 0xCDB004:
         return if_match(req, "TripleDES/CBC", {1, 2, 840, 113549, 3, 7});
      case 0xCDBB42:
         return if_match(req, "Kyber-768-90s-r3", {1, 3, 6, 1, 4, 1, 25258, 1, 11, 2});
      case 0xCE2B83:
         return if_match(req, "AES-192/GCM", {2, 16, 840, 1, 101, 3, 4, 1, 26});
      case 0xCF1CC0:
         return if_match(req, "Camellia-192/SIV", {1, 3, 6, 1, 4, 1, 25258, 3, 4, 7});
      case 0xCF62D0:
         return if_match(req, "ECKCDSA/SHA-1", {1, 2, 410, 200004, 1, 100, 4, 3});
      case 0xCFCD4C:
         return if_match(req, "Kyber-1024-r3", {1, 3, 6, 1, 4, 1, 25258, 1, 7, 3});
      case 0xD0A19C:
         return if_match(req, "PKIX.ClientAuth", {1, 3, 6, 1, 5, 5, 7, 3, 2});
      case 0xD0BA80:
         return if_match(req, "SLH-DSA-SHA2-256f", {2, 16, 840, 1, 101, 3, 4, 3, 25});
      case 0xD0BA8D:
         return if_match(req, "SLH-DSA-SHA2-256s", {2, 16, 840, 1, 101, 3, 4, 3, 24});
      case 0xD139B9:
         return if_match(req, "eFrodoKEM-1344-AES", {1, 3, 6, 1, 4, 1, 25258, 1, 17, 3});
      case 0xD18AE4:
         return if_match(req, "PKIX.OCSP", {1, 3, 6, 1, 5, 5, 7, 48, 1});
      case 0xD2369F:
         return if_match(req, "Compression.Zlib", {1, 2, 840, 113549, 1, 9, 16, 3, 8});
      case 0xD371E1:
         return if_match(req, "AES-256/OCB", {1, 3, 6, 1, 4, 1, 25258, 3, 2, 3});
      case 0xD388DC:
         return if_match(req, "PKIX.CodeSigning", {1, 3, 6, 1, 5, 5, 7, 3, 3});
      case 0xD5410A:
         return if_match(req, "GOST-34.10", {1, 2, 643, 2, 2, 19});
      case 0xD5DC40:
         return if_match(req, "AES-192/OCB", {1, 3, 6, 1, 4, 1, 25258, 3, 2, 2});
      case 0xD67F6B:
         return if_match(req, "PKIX.TimeStamping", {1, 3, 6, 1, 5, 5, 7, 3, 8});
      case 0xD69072:
         return if_match(req, "brainpool384r1", {1, 3, 36, 3, 3, 2, 8, 1, 1, 11});
      case 0xD7503B:
         return if_match(req, "AES-256/SIV", {1, 3, 6, 1, 4, 1, 25258, 3, 4, 3});
      case 0xD84E41:
         return if_match(req, "SphincsPlus-shake-256f-r3.1", {1, 3, 6, 1, 4, 1, 25258, 1, 12, 1, 6});
      case 0xD9BA9A:
         return if_match(req, "AES-192/SIV", {1, 3, 6, 1, 4, 1, 25258, 3, 4, 2});
      case 0xD9D33E:
         return if_match(req, "X520.OrganizationalUnit", {2, 5, 4, 11});
      case 0xDA6B3D:
         return if_match(req, "FrodoKEM-640-SHAKE", {1, 3, 6, 1, 4, 1, 25258, 1, 14, 1});
      case 0xDA833A:
         return if_match(req, "SHA-3(384)", {2, 16, 840, 1, 101, 3, 4, 2, 9});
      case 0xDC2546:
         return if_match(req, "frp256v1", {1, 2, 250, 1, 223, 101, 256, 1});
      case 0xDC8FA8:
         return if_match(req, "SLH-DSA-SHA2-128f", {2, 16, 840, 1, 101, 3, 4, 3, 21});
      case 0xDC8FB5:
         return if_match(req, "SLH-DSA-SHA2-128s", {2, 16, 840, 1, 101, 3, 4, 3, 20});
      case 0xDC97A0:
         return if_match(req, "X25519", {1, 3, 101, 110});
      case 0xDCDE97:
         return if_match(req, "ECGDSA/SHA-224", {1, 3, 36, 3, 3, 2, 5, 4, 3});
      case 0xDCE18A:
         return if_match(req, "ECGDSA/SHA-256", {1, 3, 36, 3, 3, 2, 5, 4, 4});
      case 0xDDD6CB:
         return if_match(req, "secp521r1", {1, 3, 132, 0, 35});
      case 0xDDDA92:
         return if_match(req, "ECGDSA/SHA-384", {1, 3, 36, 3, 3, 2, 5, 4, 5});
      case 0xDE434F:
         return if_match(req, "ClassicMcEliece_8192128f", {1, 3, 6, 1, 4, 1, 22554, 5, 1, 10});
      case 0xDF1F37:
         return if_match(req, "SphincsPlus-sha2-128s-r3.1", {1, 3, 6, 1, 4, 1, 25258, 1, 12, 2, 1});
      case 0xDF72B6:
         return if_match(req, "KeyWrap.TripleDES", {1, 2, 840, 113549, 1, 9, 16, 3, 6});
      case 0xDFBFE5:
         return if_match(req, "ECGDSA/SHA-512", {1, 3, 36, 3, 3, 2, 5, 4, 6});
      case 0xE0AFFC:
         return if_match(req, "ElGamal", {1, 3, 6, 1, 4, 1, 3029, 1, 2, 1});
      case 0xE34475:
         return if_match(req, "SLH-DSA-SHA2-192f", {2, 16, 840, 1, 101, 3, 4, 3, 23});
      case 0xE34482:
         return if_match(req, "SLH-DSA-SHA2-192s", {2, 16, 840, 1, 101, 3, 4, 3, 22});
      case 0xE37421:
         return if_match(req, "SHA-3(224)", {2, 16, 840, 1, 101, 3, 4, 2, 7});
      case 0xE48842:
         return if_match(req, "Dilithium-4x4-AES-r3", {1, 3, 6, 1, 4, 1, 25258, 1, 10, 1});
      case 0xE5609A:
         return if_match(req, "ClassicMcEliece_8192128pcf", {1, 3, 6, 1, 4, 1, 25258, 1, 18, 6});
      case 0xE65862:
         return if_match(req, "SHA-3(256)", {2, 16, 840, 1, 101, 3, 4, 2, 8});
      case 0xE8FF63:
         return if_match(req, "X520.Title", {2, 5, 4, 12});
      case 0xEA9707:
         return if_match(req, "RSA/PKCS1v15(SHA-384)", {1, 2, 840, 113549, 1, 1, 12});
      case 0xEB9782:
         return if_match(req, "XMSS-draft12", {1, 3, 6, 1, 4, 1, 25258, 1, 8});
      case 0xEBB5C6:
         return if_match(req, "eFrodoKEM-976-AES", {1, 3, 6, 1, 4, 1, 25258, 1, 17, 2});
      case 0xEC2C77:
         return if_match(req, "PKIX.IPsecUser", {1, 3, 6, 1, 5, 5, 7, 3, 7});
      case 0xED4CE0:
         return if_match(req, "PKCS9.MessageDigest", {1, 2, 840, 113549, 1, 9, 4});
      case 0xEE7377:
         return if_match(req, "SphincsPlus-sha2-192f-r3.1", {1, 3, 6, 1, 4, 1, 25258, 1, 12, 2, 4});
      case 0xEEF25C:
         return if_match(req, "GOST-34.10-2012-256/Streebog-256", {1, 2, 643, 7, 1, 1, 3, 2});
      case 0xEFADFC:
         return if_match(req, "X509v3.SubjectKeyIdentifier", {2, 5, 29, 14});
      case 0xEFCF66:
         return if_match(req, "PKIX.CertificateAuthorityIssuers", {1, 3, 6, 1, 5, 5, 7, 48, 2});
      case 0xF127F4:
         return if_match(req, "SphincsPlus-haraka-192s-r3.1", {1, 3, 6, 1, 4, 1, 25258, 1, 12, 3, 3});
      case 0xF1AB69:
         return if_match(req, "PKIX.IPsecEndSystem", {1, 3, 6, 1, 5, 5, 7, 3, 5});
      case 0xF2869C:
         return if_match(req, "SHA-224", {2, 16, 840, 1, 101, 3, 4, 2, 4});
      case 0xF2898F:
         return if_match(req, "SHA-256", {2, 16, 840, 1, 101, 3, 4, 2, 1});
      case 0xF29466:
         return if_match(req, "HSS-LMS-Private-Key", {1, 3, 6, 1, 4, 1, 25258, 1, 13});
      case 0xF2E7A4:
         return if_match(req, "eFrodoKEM-640-AES", {1, 3, 6, 1, 4, 1, 25258, 1, 17, 1});
      case 0xF38297:
         return if_match(req, "SHA-384", {2, 16, 840, 1, 101, 3, 4, 2, 2});
      case 0xF387EE:
         return if_match(req, "RSA/PKCS1v15(SHA-224)", {1, 2, 840, 113549, 1, 1, 14});
      case 0xF3A0D2:
         return if_match(req, "XMSS-draft6", {1, 3, 6, 1, 4, 1, 25258, 1, 5});
      case 0xF3D16A:
         return if_match(req, "KeyWrap.CAST-128", {1, 2, 840, 113533, 7, 66, 15});
      case 0xF4EA3D:
         return if_match(req, "GOST.IssuerSigningTool", {1, 2, 643, 100, 112});
      case 0xF567EA:
         return if_match(req, "SHA-512", {2, 16, 840, 1, 101, 3, 4, 2, 3});
      case 0xF66C2F:
         return if_match(req, "RSA/PKCS1v15(SHA-256)", {1, 2, 840, 113549, 1, 1, 11});
      case 0xF698EC:
         return if_match(req, "SHA-512-256", {2, 16, 840, 1, 101, 3, 4, 2, 6});
      case 0xF6A5ED:
         return if_match(req, "MGF1", {1, 2, 840, 113549, 1, 1, 8});
      case 0xF8D439:
         return if_match(req, "PKIX.XMPPAddr", {1, 3, 6, 1, 5, 5, 7, 8, 5});
      case 0xFA52A1:
         return if_match(req, "secp256k1", {1, 3, 132, 0, 10});
      case 0xFA597E:
         return if_match(req, "secp256r1", {1, 2, 840, 10045, 3, 1, 7});
      case 0xFB1F0D:
         return if_match(req, "PKIX.OCSP.NoCheck", {1, 3, 6, 1, 5, 5, 7, 48, 1, 5});
      case 0xFB3404:
         return if_match(req, "ML-KEM-512", {2, 16, 840, 1, 101, 3, 4, 4, 1});
      case 0xFC6090:
         return if_match(req, "SphincsPlus-shake-256s-r3.1", {1, 3, 6, 1, 4, 1, 25258, 1, 12, 1, 5});
      case 0xFC9C57:
         return if_match(req, "numsp384d1", {1, 3, 6, 1, 4, 1, 25258, 4, 2});
      case 0xFD2523:
         return if_match(req, "ML-KEM-768", {2, 16, 840, 1, 101, 3, 4, 4, 2});
      case 0xFE16F3:
         return if_match(req, "PKCS9.UnstructuredName", {1, 2, 840, 113549, 1, 9, 2});
      case 0xFE1819:
         return if_match(req, "ML-DSA-4x4", {2, 16, 840, 1, 101, 3, 4, 3, 17});
      case 0xFFB0D5:
         return if_match(req, "OpenPGP.Ed25519", {1, 3, 6, 1, 4, 1, 11591, 15, 1});
      case 0xFFF10F:
         return if_match(req, "X509v3.InvalidityDate", {2, 5, 29, 24});
      default:
         return {};
   }
   // clang-format on
}

std::unordered_map<OID, std::string> OID_Map::load_oid2str_map() {
   std::pair<const char*, std::vector<uint32_t>> dup_oids[] = {
      // clang-format off
      {"RSA", {2, 5, 8, 1, 1}},
      {"secp521r1", {1, 3, 6, 1, 4, 1, 8301, 3, 1, 2, 9, 0, 38}},
      {"gost_256A", {1, 2, 643, 2, 2, 35, 1}},
      {"gost_256A", {1, 2, 643, 2, 2, 36, 0}}
      // clang-format on
   };

   std::unordered_map<OID, std::string> map;

   for(auto& entry : dup_oids) {
      map.insert(std::make_pair(OID(std::move(entry.second)), std::string(entry.first)));
   }

   return map;
}

std::unordered_map<std::string, OID> OID_Map::load_str2oid_map() {
   std::pair<const char*, std::vector<uint32_t>> aliases[] = {
      // clang-format off
      {"Curve25519", {1, 3, 101, 110}},
      {"SM2_Sig", {1, 2, 156, 10197, 1, 301, 1}},
      {"RSA/EMSA3(MD2)", {1, 2, 840, 113549, 1, 1, 2}},
      {"RSA/EMSA3(MD5)", {1, 2, 840, 113549, 1, 1, 4}},
      {"RSA/EMSA3(SHA-1)", {1, 2, 840, 113549, 1, 1, 5}},
      {"RSA/EMSA3(SHA-256)", {1, 2, 840, 113549, 1, 1, 11}},
      {"RSA/EMSA3(SHA-384)", {1, 2, 840, 113549, 1, 1, 12}},
      {"RSA/EMSA3(SHA-512)", {1, 2, 840, 113549, 1, 1, 13}},
      {"RSA/EMSA3(SHA-224)", {1, 2, 840, 113549, 1, 1, 14}},
      {"RSA/EMSA3(SHA-512-256)", {1, 2, 840, 113549, 1, 1, 16}},
      {"RSA/EMSA3(SHA-3(224))", {2, 16, 840, 1, 101, 3, 4, 3, 13}},
      {"RSA/EMSA3(SHA-3(256))", {2, 16, 840, 1, 101, 3, 4, 3, 14}},
      {"RSA/EMSA3(SHA-3(384))", {2, 16, 840, 1, 101, 3, 4, 3, 15}},
      {"RSA/EMSA3(SHA-3(512))", {2, 16, 840, 1, 101, 3, 4, 3, 16}},
      {"RSA/EMSA3(SM3)", {1, 2, 156, 10197, 1, 504}},
      {"RSA/EMSA3(RIPEMD-160)", {1, 3, 36, 3, 3, 1, 2}},
      {"RSA/EMSA4", {1, 2, 840, 113549, 1, 1, 10}},
      {"PBES2", {1, 2, 840, 113549, 1, 5, 13}}
      // clang-format on
   };

   std::unordered_map<std::string, OID> map;

   for(auto& entry : aliases) {
      map.insert(std::make_pair(std::string(entry.first), OID(std::move(entry.second))));
   }

   return map;
}

}  // namespace Botan
