
# (C) 2022 Jack Lloyd
# (C) 2022 René Meusel, Rohde & Schwarz Cybersecurity
# Botan is released under the Simplified BSD License (see license.txt)
#
# This is a backport to have some rudimentary CI before officially switching to
# Botan's upstream GitHub Actions.

name: ci

permissions:
  contents: read
  # implicitly all other scopes not listed become none

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# cancel running workflows when new commits are being pushed in pull requests
# but not on the master branch
concurrency:
  group: ${{ github.workflow }} @ ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci:
    name: Build and Test

    strategy:
      fail-fast: false
      matrix:
        os: [ linux, macos, windows ]
        target: [ static, shared ]
        compiler: [ clang, gcc, msvc ]
        architecture: [ x86, x86_amd64 ]

        include:
          - os: linux
            host_os: ubuntu-latest
            make_tool: make
            ccache: ccache
          - os: osx
            host_os: macos-latest
            make_tool: make
            ccache: ccache
          - os: windows
            host_os: windows-2019
            make_tool: jom
            ccache: sccache

        exclude:
          - os: linux
            architecture: x86
          - os: osx
            architecture: x86
          - os: linux
            compiler: msvc
          - os: osx
            compiler: msvc
          - os: windows
            compiler: clang
          - os: windows
            compiler: gcc

    runs-on: ${{ matrix.host_os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
            path: |
              ~/.ccache
              /Users/runner/Library/Caches/ccache
            key: ${{ runner.os }}-${{ matrix.compiler }}-${{ matrix.target }}-${{ github.run_id }}
            restore-keys: |
               ${{ runner.os }}-${{ matrix.compiler }}-${{ matrix.target }}

      - name: Setup Build Host (Unix)
        run: ./src/scripts/ci/setup_gh_actions.sh ${{ matrix.target }}
        if: matrix.os != 'windows'
      - name: Setup Build Host (Windows)
        run: ./src/scripts/ci/setup_gh_actions.ps1 ${{ matrix.target }}
        if: matrix.os == 'windows'

      - run: ./src/scripts/ci_build.py --os=${{ matrix.os }} --cc='${{ matrix.compiler }}' --cpu='${{ matrix.architecture }}' --make-tool='${{ matrix.make_tool }}' --compiler-cache='${{ matrix.ccache }}' ${{ matrix.target }}
